"""Generate my controlled Gen3 dimensions and analytical BOM documents."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PARAMETERS = ROOT / "cad" / "gen3_parameters.json"
BUILD = ROOT / "cad" / "BUILD_GEN3.json"
A8B = ROOT / "analysis" / "results" / "gen27_codesign.json"
A7C = ROOT / "analysis" / "results" / "gen27_cage_circuit.json"
OUTPUTS = {
    ROOT / "cad" / "GEN3_DIMENSIONS.md": "dimensions",
    ROOT / "cad" / "GEN3_BOM.md": "bom",
}


def load(path: Path) -> dict:
    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


def render_dimensions(p: dict, build: dict, a8b: dict) -> str:
    payload = p["payload"]
    relay = p["fluxbridge"]
    stator = p["stator"]
    sectional = p["sectional_drive"]
    track = p["track"]
    fit = build["fit_checks"]
    selected = a8b["selected_candidate"]["design"]
    return f"""# Gen3 controlled dimensions

> **Generated by `tools/make_gen3_cad_docs.py`. Do not hand-edit.**  
> I use millimetres unless stated. I treat `cad/gen3_parameters.json` as authoritative and figures
> as illustrations.

## My coordinate frame

I define $+x$ as departure toward the muzzle, $y$ as lateral and $z$ as vertical. I place the
origin on the aft payload face at the retained position.

## My payload and passive interface

| Dimension | Value |
|---|---:|
| 3U envelope, x × y × z | {payload['envelope_length_x_mm']:.1f} × {payload['envelope_y_mm']:.1f} × {payload['envelope_z_mm']:.1f} |
| Corner rail width | {payload['corner_rail_width_mm']:.1f} |
| Fluxrelay start / active length | {relay['active_length_start_x_mm']:.2f} / {relay['active_length_x_mm']:.1f} |
| Lanes per face / total | {len(relay['fin_centres_across_face_mm'])} / {4 * len(relay['fin_centres_across_face_mm'])} |
| Lane centres across each face | {', '.join(f'{value:.1f}' for value in relay['fin_centres_across_face_mm'])} |
| Finished lane width / projection | {relay['fin_gross_thickness_mm']:.2f} / {relay['encapsulated_total_projection_mm']:.2f} |
| Copper rung pitch / axial width | {relay['bar_pitch_x_mm']:.2f} / {relay['bar_axial_width_mm']:.2f} |
| Magnetic ligament axial width | {relay['magnetic_ligament_axial_width_mm']:.2f} |
| Nominal lane clearance, each side | {fit['nominal_fin_clearance_per_side_mm']:.2f} |

## My primary cassette

| Dimension | Value |
|---|---:|
| Installed active length / cells per face | {stator['active_length_x_mm']:.1f} / {stator['cell_count_per_face']} |
| Pitch / electrical wavelength | {stator['cell_pitch_x_mm']:.1f} / {stator['electrical_wavelength_mm']:.1f} |
| Tooth / winding slot | {stator['tooth_axial_width_mm']:.2f} / {stator['winding_slot_axial_width_mm']:.2f} |
| Lane slots | 5 × {stator['foil_slot_width_mm']:.2f} |
| Outer legs / interior separators | {stator['outer_return_leg_width_mm']:.2f} / {stator['interior_separator_width_mm']:.2f} |
| Face footprint / outer radial height | {stator['core_face_footprint_mm']:.1f} / {stator['outer_leg_radial_height_mm']:.1f} |
| Coil turns / conductor area | {stator['coil_turns_per_cell']} / {stator['conductor_area_per_turn_mm2']:.2f} mm² |
| Copper-pack section | {stator['coil_pack_width_mm']:.1f} × {stator['coil_layer_radial_height_mm']:.1f} |
| Coil mean axial / transverse spans | {stator['coil_mean_axial_span_mm']:.1f} / {stator['coil_mean_transverse_span_mm']:.1f} |
| Two-sided gross slot fill | {100 * selected['gross_slot_fill_fraction']:.2f}% |
| Coil-to-lane-tip clearance | {fit['minimum_coil_to_fluxbridge_radial_clearance_mm']:.2f} |

## My sectional and axial package

| Dimension | Value |
|---|---:|
| Conservative active window | {sectional['active_window_cell_count']} cells / {sectional['active_window_cells_per_phase']} per phase |
| Powered travel | {sectional['powered_travel_mm']:.1f} |
| Endpoint overlap guard | {fit['endpoint_overlap_guard_mm']:.2f} |
| Track start / muzzle station | {track['start_x_mm']:.0f} / {track['muzzle_x_mm']:.0f} |
| Frame envelope / open muzzle | {track['enclosure_outer_yz_mm']:.0f} / {fit['muzzle_opening_yz_mm']:.0f} |

## Tolerances I have not defined

I have only nominal geometry. I reserve lane straightness, stator runout, core stacking, coil build,
encapsulation, vibration motion, thermal growth and four-face alignment for my later tolerance gate.
I do not treat a nominal 0.20 mm side clearance as permission to machine parts at ±0.20 mm.
"""


def render_bom(p: dict, build: dict, a8b: dict, a7c: dict) -> str:
    selected = a8b["selected_candidate"]
    interface = selected["interface"]
    primary = selected["design"]
    artifacts = build["artifacts"]
    return f"""# Gen3 analytical BOM

> **Generated by `tools/make_gen3_cad_docs.py`. Do not hand-edit.**  
> I mark analytical masses as MODEL. I do not convert unresolved CAD volume into mass.

| Qty | Item | Material / construction | Mass | Evidence | Status |
|---:|---|---|---:|---|---|
| 1 kit | Fluxrelay cage copper | Discrete rungs + root/tip buses | {interface['cage_copper_mass_kg']:.5f} kg | A8b MODEL | Alloy/temper TBD |
| 1 kit | Fluxrelay magnetic matrix | 2605SA1-class laminated ribbon screen | {interface['magnetic_matrix_mass_kg']:.5f} kg | A8b MODEL | Cutting/bonding TBD |
| 1 kit | Interface capture + encapsulation allowance | Unselected | {interface['total_increment_kg'] - interface['cage_copper_mass_kg'] - interface['magnetic_matrix_mass_kg']:.5f} kg | A8b ASSUMPTION | Detailed capture absent |
| 4 faces | Installed primary windings | Copper, 27 four-turn cells/face | {primary['installed_primary_copper_mass_kg']:.5f} kg | A8b MODEL | Insulation/leads absent |
| 4 faces | Installed stationary magnetic circuit | Laminated electrical steel placeholder | {primary['installed_stationary_core_mass_kg']:.5f} kg | A8b MODEL | Grade/stack process TBD |
| 1 | Track + 160 mm frame | Unselected | TBD | CAD geometry only | Structure analysis absent |
| 1 | Independent gate | Unselected | TBD | CAD envelope only | Actuator/latch absent |
| 1 | Sectional inverter + DC link | Unselected | TBD | A7c electrical envelope | Supplier BOM absent |
| 1 | Cooling, sensors, cables and containment | Unselected | TBD | Not modelled | Required before build |

## My controlled analytical subtotals

| Subtotal | Mass |
|---|---:|
| Passive payload interface | {interface['total_increment_kg']:.5f} kg |
| Installed active primary copper + core | {primary['installed_active_primary_mass_kg']:.5f} kg |
| Remaining margin inside my 16 kg active-material band | {16.0 - primary['installed_active_primary_mass_kg']:.5f} kg |
| A7c energized-window copper + core | {primary['primary_copper_mass_kg'] + primary['stationary_core_mass_kg']:.5f} kg |

I do **not** call my 92 g active-material margin a structure or electronics allowance. I exclude
every TBD row above. The complete assembly proxy contains
{artifacts['Bolley_Assembly_Gen3']['volume_mm3'] / 1e6:.3f} L of material-labelled solids, but I do
not treat that as a manufacturable volume or a launcher dry-mass estimate. My A7c electrical pass
remains a model result: `{a7c['disposition']}`.
"""


def rendered() -> dict[Path, str]:
    p, build, a8b, a7c = load(PARAMETERS), load(BUILD), load(A8B), load(A7C)
    return {
        path: render_dimensions(p, build, a8b)
        if kind == "dimensions"
        else render_bom(p, build, a8b, a7c)
        for path, kind in OUTPUTS.items()
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    files = rendered()
    if args.write:
        for path, content in files.items():
            path.write_text(content, encoding="utf-8")
    elif args.check:
        for path, content in files.items():
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                raise SystemExit(f"stale generated file: {path.relative_to(ROOT)}")
    else:
        for path, content in files.items():
            print(f"## {path.relative_to(ROOT)}\n\n{content}")


if __name__ == "__main__":
    main()
