"""Render the A8a axial-engagement audit."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "analysis" / "results" / "axial_engagement.json"
OUTPUT = ROOT / "docs" / "AXIAL_ENGAGEMENT.md"


def render() -> str:
    r = json.loads(INPUT.read_text(encoding="utf-8"))
    rated = r["as_drawn_rated"]
    boosted = r["as_drawn_limited_boost"]
    placed = r["best_placement_limited_boost"]
    extension = r["full_overlap_extension"]
    sectional = r["sectional_excitation"]
    return f"""# A8a axial engagement and sectional excitation

> **Generated by `tools/make_axial_engagement.py`. Do not hand-edit.**  
> Evidence class: **EXACT INTERVAL OVERLAP + CURRENT-LIMITED KINEMATIC INTEGRATION**.
> This is not transient electromagnetic FEA or measurement.

## Result

**{r['band_pass_count']}/{r['band_count']} declared bands pass. The as-drawn axial package is
rejected.** The 336 mm cage leaves the 900 mm stator during the claimed 900 mm powered travel.

| Configuration | Effective work distance | Exit velocity | End overlap | Outcome |
|---|---:|---:|---:|---|
| As drawn, 375 A | {rated['effective_work_distance_m']:.5f} m | {rated['exit_velocity_m_s']:.3f} m/s | {100*rated['final_overlap_fraction']:.1f}% | **FAIL reference** |
| As drawn, clipped at 400 A | {boosted['effective_work_distance_m']:.5f} m | {boosted['exit_velocity_m_s']:.3f} m/s | {100*boosted['final_overlap_fraction']:.1f}% | **FAIL reference** |
| Best placement, clipped at 400 A | {placed['effective_work_distance_m']:.5f} m | {placed['exit_velocity_m_s']:.3f} m/s | {100*placed['final_overlap_fraction']:.1f}% | **FAIL reference** |

The retained cage starts fully engaged, stays fully overlapped for 561.75 mm, then loses active
area linearly and reaches zero overlap before the end of travel. At fixed current that produces
only {rated['effective_work_distance_m']:.5f} m of full-force-equivalent work. The 400 A ceiling
recovers just {boosted['exit_velocity_m_s'] - rated['exit_velocity_m_s']:.3f} m/s. Centring the
travel between equal 50% overlaps is the best placement, but {placed['exit_velocity_m_s']:.3f}
m/s remains below the frozen 11.8 m/s reference band.

## Why simply extending Gen2.6 is not the answer

Full overlap needs a continuous stator through {extension['required_continuous_stator_length_m']:.5f}
m. The first complete three-phase cell count is {extension['cell_quantized_cell_count']} cells at
{extension['cell_quantized_stator_length_m']:.2f} m and
{extension['cell_quantized_active_primary_mass_kg']:.2f} kg. Whole 150 mm modules require
{extension['tile_quantized_tile_count']} tiles, {extension['tile_quantized_stator_length_m']:.2f}
m and {extension['tile_quantized_active_primary_mass_kg']:.2f} kg. Both exceed the unchanged
16 kg active-primary band.

## What survives

The sectional-drive correction is real enough to keep. A finite cage intersects at most
{sectional['maximum_simultaneously_intersected_cells']} individual cells, or
{sectional['maximum_simultaneously_intersected_tiles']} whole 150 mm tiles. At unchanged Gen2.6
copper this bounds phase resistance at {sectional['cell_window_phase_resistance_ratio_to_a7b']:.2f}
and {sectional['tile_window_phase_resistance_ratio_to_a7b']:.2f} times A7b. Both are below the
{sectional['a7b_required_phase_resistance_ratio']:.4f} ratio required to close A7b's hot-energy
corner.

That electrical correction cannot rescue the physical stroke by itself. The next candidate must
co-design active cage length and axial position, sectional winding granularity, installed core
length and conductor area. It may reuse the five-lane transverse topology, but not the as-drawn
900 mm package.

![A8a engagement profile](../analysis/figures/a8a/A8a_engagement_profile.png)

![A8a correction trade](../analysis/figures/a8a/A8a_correction_trade.png)

The complete {r['profile_artifact']['record_count']:,}-row trace is retained in
`{r['profile_artifact']['path']}`. See the immutable
[A8a run sheet](../validation/A8a_axial_engagement.md).
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.write:
        OUTPUT.write_text(content, encoding="utf-8")
    elif args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            raise SystemExit("stale generated file: docs/AXIAL_ENGAGEMENT.md")
    else:
        print(content, end="")


if __name__ == "__main__":
    main()
