"""Render my A10 Gen4-Gen6 architecture result."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "analysis" / "results" / "gen456_architecture_screen.json"
OUTPUT = ROOT / "docs" / "GEN456_ARCHITECTURE_SCREEN.md"


def status_table(result: dict) -> str:
    lines = ["| Band | Result | Status |", "|---|---:|---|"]
    for item in result["bands"]:
        value = item["value"]
        if isinstance(value, float):
            shown = f"{value:.6g}"
        elif isinstance(value, list):
            shown = ", ".join(f"{row['time_s']:.0f} s" for row in value)
        elif value is None:
            shown = "no evidence"
        else:
            shown = str(value)
        lines.append(f"| {item['id']}. {item['name']} | {shown} | **{item['status']}** |")
    return "\n".join(lines)


def render() -> str:
    result = json.loads(INPUT.read_text(encoding="utf-8"))
    k = result["kinematic_consistency"]
    frame = result["fluxframe"]
    piston = result["fluxpiston"]
    ref = piston["pressure_cases"]["reference"]
    qual = piston["pressure_cases"]["qualification"]
    strain = result["strainrail"]
    counts = result["status_counts"]
    return f"""# A10 Gen4-Gen6 architecture screen

> **Generated by `tools/make_gen456_architecture_screen.py`. Do not hand-edit.**  
> Evidence class: **FIRST-ORDER ARCHITECTURE SCREEN**. I do not call ideal work a gas-system,
> seal, structural, electromagnetic or hardware result.

## What I found

My frozen screen records **{counts['PASS']} PASS, {counts['FAIL']} FAIL, {counts['OPEN']} OPEN and
{counts['REPORT']} REPORT** bands. I do not select by pass count.

{status_table(result)}

## The requirement defect comes first

At 8 g over 0.90 m, the architecture-independent ceiling from rest is
**{k['maximum_velocity_at_8g_over_0p9m_m_s']:.4f} m/s**. Reaching exactly 12 m/s needs
**{k['acceleration_required_for_12m_s_g']:.4f} g** over 0.90 m, or
**{k['stroke_required_for_12m_s_at_8g_m']:.4f} m** at 8 g. BOL-R-002 and BOL-R-004 therefore do
not coexist exactly as written. I reject the triplet; I do not reject a machine for obeying it.

## Gen5, Fluxframe

My current 0.37136 kg interface must displace **{1000 * frame['displaced_mass_needed_for_0p25kg_net_kg']:.2f} g**,
or **{100 * frame['displaced_fraction_of_interface']:.2f}%** of its gross mass, to meet the 0.25 kg
preference on a net basis. That is a finite Gen5 target. It is not yet a saving: I withhold every
gram until a selected bus identifies the structure, heat spreader, ground strap, shield or guide
part it removes.

## Gen6, Fluxpiston

On an ideal 0.01 m2 pressure face over 0.90 m:

| Case | Velocity | Ideal work | Mean force | Mean pressure | Mean acceleration |
|---|---:|---:|---:|---:|---:|
| 4 kg screen | {ref['target_velocity_m_s']:.2f} m/s | {ref['kinetic_energy_j']:.2f} J | {ref['average_force_n']:.2f} N | {ref['mean_pressure_pa']/1000:.3f} kPa | {ref['average_acceleration_g']:.3f} g |
| 6 kg qualification | {qual['target_velocity_m_s']:.2f} m/s | {qual['kinetic_energy_j']:.2f} J | {qual['average_force_n']:.2f} N | {qual['mean_pressure_pa']/1000:.3f} kPa | {qual['average_acceleration_g']:.3f} g |

The 0.90 m swept volume is {ref['swept_volume_l']:.1f} L. The pressure is low because the full
CubeSat face supplies area; the gas volume and approximately 400 mm sealing perimeter are the
exchange. I have not modelled a valve, reservoir, compressible transient, leakage, friction,
thermal state, contamination or exit plume.

A +/-0.25 m/s electromagnetic correction needs at most
**{piston['maximum_trim_energy_j']:.3f} J** of payload kinetic-energy change in these cases. That is
small enough to justify a trim-only motor study instead of carrying Gen3's 893.412 J hot shot into
Gen6. My first 0.20 kg pressure-cup plus trim-secondary allocation passes the mass preference only
as an assumption; it excludes the parts most likely to decide the design.

## Ideas this screen stops

Strainrail would need **{strain['required_specific_energy_j_kg']:.1f} J/kg** from the entire current
interface mass to supply the 4 kg pressure-screen energy. That exceeds my frozen 350 J/kg screen,
before latch, containment, fatigue or safety margin. I reject it at the current mass.

Burn-and-drop remains outside the mechanism generations. The three reported thrust arcs take
{', '.join(f"{row['time_s']:.0f} s" for row in result['burn_and_drop'])}, but every one spends the
same 12 m/s of host delta-v. I keep it because a mission architecture may still beat a deployer;
I do not call the host impulse free.

## My disposition

- I retain Gen4 for A9 switching and packaged-system closure.
- I promote Gen5 only to a bus-specific displaced-mass and multifunctional qualification gate.
- I promote Gen6 only to pressure-transient, seal/contact, rear-face structure, trim-authority and
  six-degree-of-freedom exit gates.
- I correct the inconsistent requirement triplet by a separate ADR before comparing later results.

See my immutable [A10 declaration](../validation/A10_architecture_screen.md),
[generation definitions](GENERATIONS.md) and [unknown-unknown search](UNKNOWN_UNKNOWNS.md).
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.write:
        OUTPUT.write_text(rendered, encoding="utf-8")
    elif args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            raise SystemExit("stale generated file: docs/GEN456_ARCHITECTURE_SCREEN.md")
    else:
        print(rendered, end="")


if __name__ == "__main__":
    main()
