"""Render the A8b Gen2.7 Fluxrelay co-design result."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "analysis" / "results" / "gen27_codesign.json"
OUTPUT = ROOT / "docs" / "GEN27_CODESIGN.md"


def render() -> str:
    result = json.loads(INPUT.read_text(encoding="utf-8"))
    selected = result["selected_candidate"]
    design = selected["design"]
    interface = selected["interface"]
    rated = selected["rated"]
    sectional = selected["sectional"]
    field = selected["field_surrogate"]
    demands = selected["continuous_demand_by_band"]
    corners = selected["corners"]

    worst_reference = max(
        corner["reference"]["maximum_source_energy_j"] for corner in corners
    )
    worst_qualification = max(
        corner["qualification"]["maximum_source_energy_j"] for corner in corners
    )
    minimum_secondary_efficiency = min(
        corner[case]["minimum_secondary_only_efficiency"]
        for corner in corners
        for case in ("reference", "qualification")
    )
    maximum_cage_rise = max(
        corner[case]["maximum_cage_copper_rise_k"]
        for corner in corners
        for case in ("reference", "qualification")
    )
    maximum_voltage = max(corner["maximum_required_dc_link_v"] for corner in corners)
    controlling = sorted(demands.items(), key=lambda item: item[1], reverse=True)[:5]
    controlling_rows = "\n".join(
        f"| {name.replace('_', ' ').title()} | {demand:.4f} | "
        f"{100 * (1.0 - demand):.2f}% |"
        for name, demand in controlling
    )

    return f"""# A8b Gen2.7 Fluxrelay co-design

> **Generated by `tools/make_gen27_codesign.py`. Do not hand-edit.**  
> Evidence class: **COUPLED AXIAL / SECTIONAL-WINDING / CAGE-CIRCUIT MODEL**.  
> I use current-scaled A6g field values as surrogates here; I do not present this as a new
> nonlinear field solve, transient electromagnetic FEA or measurement.

## What I found

**I found {result['feasible_candidate_count']} of {result['candidate_count']:,} candidates passing
every declared hard band.** I fully evaluated {result['fully_evaluated_candidate_count']} candidates
that passed the geometric, mass, winding and field-surrogate precheck, including all four robustness
corners over both 21 by 21 CG grids. By my deterministic minimax rule, I selected
`{result['selected_candidate_id']}`.

| Selected quantity | A8b value | Frozen band | Outcome |
|---|---:|---:|---|
| Cells per face channel | {design['total_cells_per_channel']} | complete 3-phase lattice | PASS |
| Cell pitch | {1e3 * design['cell_pitch_m']:.1f} mm | searched | selected |
| Installed stator length | {design['active_stator_length_m']:.4f} m | full 0.90 m travel + guards | PASS |
| Passive cage length | {1e3 * interface['active_cage_length_m']:.1f} mm | 200–336 mm | PASS |
| End engagement guard | {1e3 * interface['end_overlap_guard_m']:.2f} mm | >=2.25 mm | PASS |
| Rated phase current | {rated['phase_current_rms_a']:.0f} A | <=400 A | PASS |
| Conductor area per turn | {1e6 * design['conductor_area_per_turn_m2']:.1f} mm2 | current density <=40 A/mm2 | PASS |
| Installed active primary | {design['installed_active_primary_mass_kg']:.3f} kg | <=16.0 kg | PASS |
| Spacecraft interface increment | {interface['total_increment_kg']:.3f} kg | <=0.40 kg | PASS |
| Active-window phase resistance | {sectional['phase_resistance_ratio_to_a7b']:.4f} x A7b | <=0.8202 diagnostic | PASS |
| Worst reference source energy | {worst_reference:.2f} J | <=900 J | PASS |
| Worst qualification source energy | {worst_qualification:,.2f} J | <=1,500 J | PASS |
| Minimum secondary efficiency | {100 * minimum_secondary_efficiency:.2f}% | >=50% | PASS |
| Worst cage copper rise | {maximum_cage_rise:.2f} K | <=20 K | PASS |
| Required DC link | {maximum_voltage:.2f} V | <=48 V and >=10% margin | PASS |
| Predicted stationary-core peak | {field['predicted_stationary_core_peak_t']:.4f} T | <=1.55 T | PASS surrogate |

## The machine I selected

I gave each of the four face channels 27 stationary cells in a repeating three-phase lattice.
With a 45.3 mm pitch, I obtain a 1.2231 m installed primary. I start the 318.6 mm five-lane passive
cage 2.25 mm inside the payload end and finish the 900 mm powered travel with another 2.25 mm of
engagement. The cage can intersect at most {sectional['maximum_intersected_cells']} cells at once,
so I energise no more than
{sectional['simultaneously_energized_cells_per_phase']} cells per phase in each channel.

I use that distinction to close A8a without pretending the unused primary disappears. I count all
27 cells against the installed-mass band, while only the active window contributes pulse
copper/core loss and temperature. At my selected 10.4 mm2 conductor area, active-window resistance
falls to
{sectional['phase_resistance_ratio_to_a7b']:.4f} of A7b and the worst hot reference corner falls to
{worst_reference:.2f} J.

## Why I selected this point

I did not select on one attractive number. I minimised the weakest continuous hard band, then
installed primary mass, then hot reference energy. My selected point's five tightest demands are:

| Band | Normalized demand | Remaining model margin |
|---|---:|---:|
{controlling_rows}

I found a narrow, coupled solution rather than an oversized optimum. More pitch or copper breaks
my 16 kg primary limit; less copper or cage length raises resistance and source energy; more
current consumes the already narrow nonlinear-field surrogate margin. My feasible island contains
only 27-cell candidates, 44.8–45.6 mm pitch, 375–383 A and 10.2–10.8 mm2 conductors.

## What I still need to close

- I must solve the selected 380 A point in A6h on fresh coarse/fine/alternate nonlinear meshes. The
  1.534 T stationary-core value is only a current-scaled A6g estimate.
- I must rerun the selected point in A7c from A6h field and inductance outputs rather than A8b
  surrogates.
- I have not yet closed cell handoff, end effects, force ripple, inverter partitioning or fault
  containment; they remain outside the model.
- I have not included structure, winding end turns, cooling, fasteners or power electronics in the
  15.91 kg active-primary accounting.
- I may encode this point in Gen3 CAD for fit inspection, but I will not use CAD to turn these
  model margins into hardware evidence.

![A8b feasible design island](../analysis/figures/a8b/A8b_feasible_island.png)

![A8b selected normalized margins](../analysis/figures/a8b/A8b_selected_margins.png)

![A8b selected axial package](../analysis/figures/a8b/A8b_axial_package.png)

I retain my complete {result['candidate_artifact']['record_count']:,}-candidate artifact at
`{result['candidate_artifact']['path']}`, SHA-256
`{result['candidate_artifact']['sha256']}`. See the immutable
[A8b run sheet](../validation/A8b_gen27_codesign.md).
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.write:
        OUTPUT.write_text(content, encoding="utf-8")
    elif args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            raise SystemExit("stale generated file: docs/GEN27_CODESIGN.md")
    else:
        print(content, end="")


if __name__ == "__main__":
    main()
