"""Render the A6g Gen2.6 Quintweb nonlinear field result."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "analysis" / "results" / "gen26_field.json"
PARAMETERS = ROOT / "cad" / "gen26_field_parameters.json"
OUTPUT = ROOT / "docs" / "GEN26_FIELD.md"


def mark(value: bool) -> str:
    return "PASS" if value else "**FAIL**"


def render() -> str:
    r = json.loads(INPUT.read_text(encoding="utf-8"))
    p = json.loads(PARAMETERS.read_text(encoding="utf-8"))
    x = r["physics_band_extrema"]
    b = r["bands"]
    c = r["convergence"]
    interface = p["interface_accounting"]
    return f"""# A6g Gen2.6 Quintweb field gate

> **Generated by `tools/make_gen26_field.py`. Do not hand-edit.**  
> Evidence class: **THREE-MESH 2D NONLINEAR RMS-EQUIVALENT MAGNETOSTATIC FEA**.
> Physical bands use the worst of all three meshes. This is not measurement or force evidence.

## Result

**{r['band_pass_count']}/{r['band_count']} declared magnetic bands pass.** The payload mass target
and preference fail; the absolute mass limit passes narrowly.

| Quantity | Controlled result | Frozen band | Outcome |
|---|---:|---:|---:|
| Base-to-fine mean-field change | {100*c['base_to_fine_mean_slot_field_change_fraction']:.3f}% | <=2.000% | {mark(b['mesh_mean_field_convergence'])} |
| Base-to-fine coenergy change | {100*c['base_to_fine_coenergy_change_fraction']:.3f}% | <=4.000% | {mark(b['mesh_coenergy_convergence'])} |
| Boundary mean-field change | {100*c['base_to_expanded_boundary_mean_slot_field_change_fraction']:.3f}% | <=2.000% | {mark(b['outer_boundary_sensitivity'])} |
| Worst-mesh mean-field range | {x['minimum_mean_tooth_slice_field_rms_t']:.4f}–{x['maximum_mean_tooth_slice_field_rms_t']:.4f} T | 0.7200–0.8600 T | {mark(b['mean_field_lower'] and b['mean_field_upper'])} |
| Worst slot imbalance / height CV | {100*x['maximum_slot_to_slot_flux_imbalance_fraction']:.3f}% / {100*x['maximum_active_height_field_coefficient_of_variation']:.3f}% | <=5% / <=15% | {mark(b['slot_flux_balance'] and b['active_height_field_uniformity'])} |
| Worst moving-material peak | {x['maximum_inferred_magnetic_ligament_field_t']:.4f} T | <=1.4500 T | {mark(b['magnetic_ligament_field'])} |
| Worst stationary-core peak | {x['maximum_stationary_core_field_t']:.4f} T | <=1.5500 T | {mark(b['stationary_core_field'])} |
| Fine inductance ratio to A3g | {r['fine_inductance_ratio_to_a3g']:.4f} | 0.6800–1.4000 | {mark(b['inductance_lower'] and b['inductance_upper'])} |
| Worst source / nonlinear closure | {x['maximum_source_current_residual_fraction']:.3e} / {x['maximum_nonlinear_relative_solution_change']:.3e} | <=1e-10 / <=1e-4 | {mark(b['source_current_closure'] and b['nonlinear_convergence'])} |
| Interface increment | {interface['total_interface_increment_kg']:.5f} kg | absolute <=0.40000 kg | PASS |

The fifth blade does what A7a needed without breaking the field. Moving-material peak is
{100*(1-x['maximum_inferred_magnetic_ligament_field_t']/1.45):.2f}% below its limit and all three
mesh means remain more than {100*(x['minimum_mean_tooth_slice_field_rms_t']/0.72-1):.2f}% above the
floor. The stationary return is closer: {x['maximum_stationary_core_field_t']:.4f} T leaves
{1000*(1.55-x['maximum_stationary_core_field_t']):.1f} mT.

## Disposition

**{r['disposition'].replace('_', ' ')}.** A6g opens A7b and Gen3 CAD; it does not close either.
The pass has only {1000*interface['absolute_interface_margin_kg']:.2f} g of geometric payload-mass
margin, and worst nonlinear closure is {x['maximum_nonlinear_relative_solution_change']:.3e}.

![A6g fine field](../analysis/figures/a6g/A6g_field_magnitude.png)

![A6g blade distribution](../analysis/figures/a6g/A6g_blade_fields.png)

![A6g convergence](../analysis/figures/a6g/A6g_convergence.png)

See the immutable [A6g run sheet](../validation/A6g_gen26_quintweb.md).
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.write:
        OUTPUT.write_text(content, encoding="utf-8")
    elif args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            raise SystemExit("stale generated file: docs/GEN26_FIELD.md")
    else:
        print(content, end="")


if __name__ == "__main__":
    main()
