"""Render the A3a topology-screen summary from its committed JSON result."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "analysis" / "results" / "topology_screen.json"
OUTPUT = ROOT / "docs" / "TOPOLOGY_SCREEN.md"


def render() -> str:
    with INPUT.open(encoding="utf-8") as handle:
        result = json.load(handle)
    corner = result["candidates"]["corner_l_return"]
    fin = result["candidates"]["opposed_through_flux_fin"]
    induction = result["candidates"]["single_sided_induction_lane"]
    maxwell = result["maxwell_stress_screen"]
    rows = [
        (
            "Corner L-return",
            corner["active_area_m2_per_channel"],
            "field-dependent",
            corner["disposition"],
        ),
        (
            "Opposed through-flux fin",
            fin["active_area_m2_per_channel"],
            f"{fin['interface_increment_kg']:.3f}",
            fin["disposition"],
        ),
        (
            "Single-sided induction lane",
            induction["active_area_m2_per_channel"],
            f"{induction['interface_increment_kg']:.3f}",
            induction["disposition"],
        ),
    ]
    table = "\n".join(
        f"| {name} | {area * 1e4:.2f} | {mass} | {disposition.replace('_', ' ')} |"
        for name, area, mass, disposition in rows
    )
    failed = [name for name, passed in result["bands"].items() if not passed]
    failed_text = ", ".join(name.replace("_", " ") for name in failed) or "none"
    corner_outcome = (
        "passes"
        if result["bands"]["corner_preferred_mass_supports_ideal_equal_component_field"]
        else "fails"
    )
    return f"""# A3a flux-path topology screen

> **Generated by `tools/make_topology_screen.py`. Do not hand-edit.**  
> Evidence class: **ANALYTICAL MODEL OUTPUT from ASSUMPTION inputs**. I do not present this as FEA or measurement.

## What I found

The original 0.50 mm equivalent-thickness rail is not a physical flux-path definition. Once an
L-shaped corner return is sized to carry flux, its mass depends strongly on normal gap field.
The preferred 0.25 kg interface gate permits only **{corner['preferred_mass_normal_flux_cap_t']:.3f} T**
normal flux; the 0.40 kg kill gate permits **{corner['kill_mass_normal_flux_cap_t']:.3f} T**.

The optimistic equal-component Maxwell-stress screen for the A2 load is
**{maxwell['optimistic_equal_component_flux_t']:.3f} T** normal and tangential field over the
50%-duty local tooth faces. The corner return therefore **{corner_outcome}** the preferred-mass
lower-bound band. Its hard-mass field cap is
**{corner['kill_flux_cap_to_ideal_equal_component_ratio']:.2f}×** the already-optimistic minimum,
before leakage, saturation and cover-gap penalties.

| Candidate | Active area per channel, cm² | Interface increment, kg | Disposition |
|---|---:|---:|---|
{table}

The opposed fin and induction lane preserve the required **{result['required_area_at_band_m2_per_channel'] * 1e4:.2f} cm²**
per-channel area while remaining below the preferred mass gate. This keeps Bolley alive, but does
not establish that either can make thrust.

## What I found against my declared bands

**{result['band_pass_count']}/{result['band_count']} A3a bands pass.** Failed bands: {failed_text}.

## What I decided

1. Do not spend nonlinear-FEA effort on the corner L-return as the primary topology.
2. Fit-check an opposed through-flux fin/tab cross-section first; only then run nonlinear FEA.
3. Retain the single-sided induction lane as the mechanically simpler fallback and build its
   transient force/loss model in parallel with interface fit work.
4. Do not quote the A1 0.229 kg equivalent-thickness result as a designed rail mass.

## Still open

- Double-sided stator access around the fin/tab is unproven.
- No nonlinear force, ripple, normal-force or voltage solution exists.
- No induction slip, secondary-loss or thermal solution exists.
- No candidate has passed a CubeSat envelope, rail-contact or provider review.

See the [dimensioned screening cells](../cad/a3a_unit_cells.svg) and the immutable
[A3a run sheet](../validation/A3a_flux_path_screen.md).
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.write:
        OUTPUT.write_text(rendered, encoding="utf-8")
    elif args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            raise SystemExit("stale generated file: docs/TOPOLOGY_SCREEN.md")
    else:
        print(rendered, end="")


if __name__ == "__main__":
    main()
