"""Render the A3e serpentine-stator circuit screen."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "analysis" / "results" / "stator_circuit.json"
OUTPUT = ROOT / "docs" / "STATOR_CIRCUIT.md"


def render() -> str:
    with INPUT.open(encoding="utf-8") as handle:
        result = json.load(handle)
    geometry = result["geometry"]
    rated = result["rated_magnetic_circuit"]
    winding = result["winding"]
    mass = result["active_electromagnetic_mass"]
    drive = result["drive"]
    reference = result["reference_case"]
    qualification = result["qualification_case"]
    ref_energy = reference["worst_source_energy_point"]
    ref_power = reference["worst_peak_power_point"]
    qual_energy = qualification["worst_source_energy_point"]
    qual_power = qualification["worst_peak_power_point"]
    failed = [name.replace("_", " ") for name, passed in result["bands"].items() if not passed]
    failed_text = ", ".join(failed) if failed else "none"
    return f"""# A3e serpentine stator and circuit screen

> **Generated by `tools/make_stator_circuit.py`. Do not hand-edit.**  
> Evidence class: **LUMPED MAGNETIC/CIRCUIT MODEL OUTPUT**. This is not field FEA, detailed CAD
> or measurement.

## The flux path

One transverse series loop crosses all four foil slots in each axial phase cell before returning
through two 3 mm outer legs and a 3 mm back yoke. Interior separators carry flux straight across;
they do not turn two fin fluxes into the impossible A3b1 shared throats.

| Quantity | Result |
|---|---:|
| Channels / phases / total phase cells | {geometry['channel_count']} / {geometry['phase_count']} / {geometry['total_phase_cells']} |
| Active stator length | {geometry['active_stator_length_m']:.3f} m |
| Face footprint | {geometry['slot_array_width_m'] * 1e3:.1f} mm |
| Rated gap / outer-yoke field | {rated['field_rms_t']:.2f} / {rated['core_field_rms_t']:.2f} T RMS |
| Rated MMF | {rated['mmf_a_turn']:.0f} A-turn |
| Turns / rated phase current | {winding['turns_per_cell']} / {rated['phase_current_rms_a']:.1f} A RMS |
| Copper current density | {winding['rated_current_density_a_m2'] / 1e6:.2f} A/mm² |
| Phase resistance / inductance | {winding['phase_resistance_ohm'] * 1e3:.2f} mΩ / {rated['phase_inductance_h'] * 1e6:.1f} µH |
| Active copper / steel / total | {mass['copper_kg']:.1f} / {mass['electrical_steel_kg']:.1f} / {mass['total_kg']:.1f} kg |
| Maximum required DC link | {drive['maximum_model_required_dc_link_v']:.1f} V |
| Margin on nominal {drive['nominal_dc_link_v']:.0f} V link | {100 * drive['nominal_dc_link_margin_fraction']:.1f}% |
| Maximum electrical frequency | {drive['maximum_model_frequency_hz']:.1f} Hz |

## Integrated shots

| Quantity | 4 kg reference | 6 kg qualification |
|---|---:|---:|
| Worst source energy | {ref_energy['source_energy_j']:.1f} J | {qual_energy['source_energy_j']:.1f} J |
| Payload mechanical energy | {ref_energy['mechanical_energy_j']:.1f} J | {qual_energy['mechanical_energy_j']:.1f} J |
| Source-to-payload efficiency | {100 * ref_energy['source_to_payload_efficiency']:.1f}% | {100 * qual_energy['source_to_payload_efficiency']:.1f}% |
| Worst peak DC power | {ref_power['peak_dc_power_w'] / 1000:.2f} kW | {qual_power['peak_dc_power_w'] / 1000:.2f} kW |
| Worst copper rise per shot | {ref_energy['copper_adiabatic_temperature_rise_k']:.3f} K | {qual_energy['copper_adiabatic_temperature_rise_k']:.3f} K |

## Declared-band result

**{result['band_pass_count']}/{result['band_count']} A3e bands pass.** Failed bands: {failed_text}.

Disposition: **{result['disposition'].replace('_', ' ')}**.

This closes the first explicit iron/copper/source accounting. It does not close the field: a
finite-element solve must now show that a 20 mm serpentine cell actually produces the assumed
travelling wave after leakage, ends, slots and mutual coupling. CAD may proceed because the loop,
winding window, mass and circuit now have declared dimensions rather than a blue block in a sketch.

See the immutable [A3e run sheet](../validation/A3e_serpentine_stator.md).
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.write:
        OUTPUT.write_text(rendered, encoding="utf-8")
    elif args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            raise SystemExit("stale generated file: docs/STATOR_CIRCUIT.md")
    else:
        print(rendered, end="")


if __name__ == "__main__":
    main()
