"""Render my A5e Gen3 CAD-fit result."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "analysis" / "results" / "gen3_cad_fit.json"
OUTPUT = ROOT / "docs" / "GEN3_CAD_FIT.md"


def render() -> str:
    result = json.loads(INPUT.read_text(encoding="utf-8"))
    g = result["geometry"]
    m = result["mass_trace"]
    a = result["artifacts"]
    failed = ", ".join(name.replace("_", " ") for name in result["failed_bands"]) or "none"
    return f"""# A5e Gen3 Fluxrelay CAD and fit gate

> **Generated by `tools/make_gen3_cad_fit.py`. Do not hand-edit.**  
> Evidence class: **PARAMETRIC CAD + EXACT NOMINAL SOLID INTERSECTION + ARCHIVE MANIFEST**.
> I do not present this as a tolerance study, structural design or manufacturing release.

## What I found

**{result['band_pass_count']}/{result['band_count']} frozen bands pass.** Failed bands: {failed}.

| Quantity | My Gen3 result |
|---|---:|
| Controlled selected point | `{result['selected_candidate_id']}` |
| Payload envelope | {g['payload_envelope_mm'][0]:.1f} × {g['payload_envelope_mm'][1]:.1f} × {g['payload_envelope_mm'][2]:.1f} mm |
| Active cage start / length | {g['active_cage_start_mm']:.2f} / {g['active_cage_length_mm']:.1f} mm |
| Finished lanes per face / width | {g['finished_lane_count_per_face']} / {g['finished_lane_width_mm']:.2f} mm |
| Lane side clearance | {g['nominal_lane_clearance_per_side_mm']:.2f} mm |
| Stator length / pitch / cell count | {g['active_stator_length_mm']:.1f} / {g['cell_pitch_mm']:.1f} mm / {g['cell_count_per_face']} |
| Conservative active window | {g['active_window_cell_count']} cells |
| Two-sided gross winding fill | {100 * g['gross_winding_slot_fill_fraction']:.2f}% |
| Coil-to-lane radial clearance | {g['coil_to_lane_radial_clearance_mm']:.2f} mm |
| Endpoint engagement guard | {g['endpoint_overlap_guard_mm']:.2f} mm |
| Payload/stator intersection, four faces | {g['payload_stator_intersection_all_faces_mm3']:.6f} mm³ |
| Coil/core intersection, one face | {g['coil_core_intersection_per_face_mm3']:.6f} mm³ |
| Adjacent-coil overlap, one face | {g['adjacent_coil_overlap_per_face_mm3']:.6f} mm³ |
| Muzzle opening / frame envelope | {g['muzzle_opening_yz_mm']:.0f} / {g['assembly_frame_yz_mm']:.0f} mm |
| CAD / A8b installed copper volume | {g['cad_coil_volume_mm3']:.3f} / {g['a8b_installed_copper_volume_mm3']:.3f} mm³ |
| Copper-volume relative error | {g['coil_volume_relative_error']:.3e} |
| Interface / active-primary mass | {m['interface_increment_kg']:.6f} / {m['installed_active_primary_kg']:.6f} kg |
| Active-material margin to 16 kg | {1000 * m['unallocated_active_material_margin_kg']:.3f} g |
| STEP / STL / inspected renders | {a['step_count']} / {a['stl_count']} / {a['render_count']} |

## What I closed in A5e

I replaced the historical 900 mm Gen2 package with a new, dimension-controlled Gen3 build. The
CAD now carries my exact 318.6 mm five-lane Fluxrelay cage, 27 cells at 45.3 mm pitch, four
independently arranged stator faces and a distinct nine-cell sectional window. The cage preserves
its full 2.25 mm overlap guard after 900 mm of travel.

I routed adjacent winding packs in alternating radial layers. Their exact nominal intersection is
zero, their intersection with the magnetic core is zero, and the nearest pack clears the passive
lane tip by 0.75 mm. My complete winding-envelope volume reproduces A8b's installed copper volume
to numerical round-off.

The full-length lanes remain the homogenized A6h/A7c representation. I also built a separate
100 mm coupon with fifty resolved web/rung periods so I do not disguise the homogenization as
manufacturing detail.

## Download and regenerate

- [My Gen3 STEP masters](../{a['step_archive']})
- [My Gen3 STL previews](../{a['stl_archive']})

I fix archive timestamps and verify every member by size and SHA-256. The native construction source
is `cad/build_gen3.py`; exact solid counts, volumes, bounds and checks are in
`cad/BUILD_GEN3.json`.

## What I decided next

**{result['disposition'].replace('_', ' ')}.**

I have closed nominal geometry, not a build release. I still need individual turns, insulation,
leads, lamination detail, a real cage layup and root capture, tolerances, thermal growth, structure,
containment, cooling, sensors, wiring, gate hardware and a full packaged mass. My remaining 91.896 g
inside the active-material band is not an allowance for those systems. A9 must also close current
rise, cell handoff, force ripple, failed-cell behavior and exit timing.

![My Gen3 retained assembly](../cad/renders/gen3/01_gen3_hero.png)

![My resolved Fluxrelay lane](../cad/renders/gen3/03_discrete_fluxrelay_lane.png)

![My nine-cell sectional window](../cad/renders/gen3/06_sectional_active_window.png)

![My 900 mm endpoint engagement](../cad/renders/gen3/09_endpoint_engagement.png)

See my immutable [A5e run sheet](../validation/A5e_gen3_cad.md) and
[manual-detail ledger](../cad/GEN3_MANUAL_DETAILS.md).
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.write:
        OUTPUT.write_text(rendered, encoding="utf-8")
    elif args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            raise SystemExit("stale generated file: docs/GEN3_CAD_FIT.md")
    else:
        print(rendered, end="")


if __name__ == "__main__":
    main()
