"""Render the A3c Fluxfoil thin-sheet screen from its committed JSON result."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "analysis" / "results" / "induction_screen.json"
OUTPUT = ROOT / "docs" / "INDUCTION_SCREEN.md"


def render() -> str:
    with INPUT.open(encoding="utf-8") as handle:
        result = json.load(handle)
    geometry = result["geometry"]
    mass = result["moving_mass"]
    rated = result["rated_channel"]
    shot = result["qualification_shot"]
    worst = shot["worst_secondary_heat_point"]
    failed = [name.replace("_", " ") for name, passed in result["bands"].items() if not passed]
    failed_text = ", ".join(failed) if failed else "none"
    return f"""# A3c Fluxfoil induction screen

> **Generated by `tools/make_induction_screen.py`. Do not hand-edit.**  
> Evidence class: **ANALYTICAL THIN-SHEET MODEL OUTPUT**. This is not field FEA, a stator
> design or measurement.

## Outcome

Fluxfoil replaces the rejected moving magnetic circuit with four continuous aluminium fins per
face. A symmetric travelling field induces closed eddy-current loops in each fin; both stators
produce axial force in the same direction while their normal attraction nominally cancels.

| Quantity | Result |
|---|---:|
| Payload-side interface increment | {mass['interface_increment_kg'] * 1e3:.1f} g |
| Projection / nominal reserve | {geometry['total_projection_from_rail_plane_m'] * 1e3:.2f} / {geometry['nominal_protrusion_margin_m'] * 1e3:.2f} mm |
| Slot-array footprint / usable-face share | {geometry['stationary_slot_array_footprint_m'] * 1e3:.1f} mm / {100 * geometry['projected_usable_face_fraction']:.1f}% |
| Rated channel force | {rated['force_n']:.1f} N |
| External travelling field | 0.500 T RMS |
| Required slip speed | {rated['slip_speed_m_s']:.3f} m/s |
| Sheet reaction number | {rated['sheet_reaction_number']:.3f} |
| RMS conductor current density | {rated['current_density_rms_a_m2'] / 1e6:.1f} MA/m² |
| Slip frequency / skin depth | {rated['slip_frequency_hz']:.1f} Hz / {rated['skin_depth_m'] * 1e3:.2f} mm |
| Rated-channel adiabatic rise for 150 ms | {rated['adiabatic_temperature_rise_k']:.2f} K |
| Normal force per side | {rated['normal_force_per_side_n']:.1f} N |
| Residual normal force at 1% side-to-side field mismatch | {rated['unbalanced_normal_force_n']:.1f} N |
| Rated start-to-terminal field frequency | {rated['start_electrical_frequency_hz']:.1f}–{rated['terminal_electrical_frequency_hz']:.1f} Hz |
| Qualification exit speed / stroke time | {shot['exit_velocity_m_s']:.3f} m/s / {shot['stroke_time_s'] * 1e3:.1f} ms |
| Worst-CG secondary heat | {worst['secondary_heat_j']:.1f} J |
| Worst-CG secondary-only shot efficiency | {100 * worst['secondary_only_shot_efficiency']:.1f}% |
| Worst-CG peak air-gap power | {worst['peak_airgap_power_w'] / 1000:.2f} kW |

## Declared-band result

**{result['band_pass_count']}/{result['band_count']} A3c bands pass.** Failed bands: {failed_text}.

Disposition: **{result['disposition'].replace('_', ' ')}**.

## What this establishes

The passive conductor is not the obvious bottleneck at the frozen force and pulse. The required
slip, current density, local heating, frequency chirp, normal-force mismatch and moving mass all
fit their predeclared screens. Unlike the reluctance comb, this result does not require flux to
turn through a thin moving or shared pole throat.

The 0.5 T travelling field is still an assumption. Gen1 now needs an explicit double-sided stator,
winding window, flux-return section and inverter model. End and edge effects must then be solved by
a field method before a coupon is ordered.

See the immutable [A3c run sheet](../validation/A3c_fluxfoil_induction.md) and
[ADR-007](adr/007-fluxfoil-baseline.md).
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.write:
        OUTPUT.write_text(rendered, encoding="utf-8")
    elif args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            raise SystemExit("stale generated file: docs/INDUCTION_SCREEN.md")
    else:
        print(rendered, end="")


if __name__ == "__main__":
    main()
