"""Render the A3g robust Fluxbridge optimisation result."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "analysis" / "results" / "fluxbridge_optimization.json"
A3F = ROOT / "analysis" / "results" / "fluxbridge_cage.json"
OUTPUT = ROOT / "docs" / "FLUXBRIDGE_OPTIMIZATION.md"


def find_corner(candidate: dict, clearance: float, conductance: float, h: float) -> dict:
    target = {
        "clearance_per_side_m": clearance,
        "cage_sheet_conductance_multiplier": conductance,
        "stationary_core_h_multiplier": h,
    }
    return next(record for record in candidate["corners"] if record["corner"] == target)


def render() -> str:
    result = json.loads(INPUT.read_text(encoding="utf-8"))
    a3f = json.loads(A3F.read_text(encoding="utf-8"))
    selected = result["selected_candidate"]
    design = selected["design"]
    nominal = find_corner(selected, 0.0002, 1.0, 1.0)
    worst = max(
        selected["corners"],
        key=lambda record: record["qualification"]["maximum_source_energy_j"],
    )
    a3f_ref = a3f["reference_case"]["worst_source_energy_point"]
    a3f_qual = a3f["qualification_case"]["worst_source_energy_point"]
    nominal_ref = nominal["reference"]
    nominal_qual = nominal["qualification"]
    worst_ref = worst["reference"]
    worst_qual = worst["qualification"]
    energy_reduction = 1.0 - (
        nominal_qual["maximum_source_energy_j"] / a3f_qual["source_energy_j"]
    )
    return f"""# A3g robust Fluxbridge optimisation

> **Generated by `tools/make_fluxbridge_optimization.py`. Do not hand-edit.**  
> Evidence class: **ROBUST CONSTRAINED ANALYTICAL DESIGN-SPACE SEARCH**. It inherits A3f's
> homogenized cage and lumped magnetic assumptions.

## What I selected

I evaluated **{result['candidate_count']} nominal candidates**, each at
**{result['corners_per_candidate']} robustness corners** and 441 CG points for both payload cases:
{result['total_candidate_corner_evaluations']} candidate-corner evaluations. Exactly
**{result['feasible_candidate_count']} candidates** pass every band at every corner.

I selected **{result['selected_candidate_id']}**.

| Frozen Gen2 quantity | Selected value |
|---|---:|
| Cell pitch / tooth / winding slot | {design['cell_pitch_m'] * 1e3:.0f} / {design['tooth_width_m'] * 1e3:.0f} / {design['winding_slot_width_m'] * 1e3:.0f} mm |
| Cells per channel / phase | {design['total_cells_per_channel']} / {design['cells_per_phase']} |
| Active stator length | {design['active_stator_length_m']:.3f} m |
| Electrical wavelength | {design['electrical_wavelength_m'] * 1e3:.0f} mm |
| Equivalent / tooth / ligament field | {design['equivalent_field_rms_t']:.2f} / {design['tooth_field_rms_t']:.3f} / {design['magnetic_ligament_field_rms_t']:.3f} T RMS |
| Turns / conductor area | 4 / {design['conductor_area_per_turn_m2'] * 1e6:.2f} mm² |
| Mean turn length / two-sided slot fill | {design['mean_turn_length_m'] * 1e3:.0f} mm / {100 * design['gross_slot_fill_fraction']:.1f}% |
| Phase resistance | {design['phase_resistance_ohm'] * 1e3:.3f} mΩ |
| Active copper / core / total | {design['primary_copper_mass_kg']:.3f} / {design['stationary_core_mass_kg']:.3f} / {design['active_primary_mass_kg']:.3f} kg |

## Nominal and degraded corners

| Quantity | Nominal reference | Nominal qualification | Worst declared corner, qualification |
|---|---:|---:|---:|
| Source energy | {nominal_ref['maximum_source_energy_j']:.1f} J | {nominal_qual['maximum_source_energy_j']:.1f} J | {worst_qual['maximum_source_energy_j']:.1f} J |
| Source-to-payload efficiency | {100 * nominal_ref['minimum_source_to_payload_efficiency']:.1f}% | {100 * nominal_qual['minimum_source_to_payload_efficiency']:.1f}% | {100 * worst_qual['minimum_source_to_payload_efficiency']:.1f}% |
| Peak DC power | {nominal_ref['maximum_peak_dc_power_w'] / 1000:.2f} kW | {nominal_qual['maximum_peak_dc_power_w'] / 1000:.2f} kW | {worst_qual['maximum_peak_dc_power_w'] / 1000:.2f} kW |
| Required DC link | {nominal_ref['maximum_required_dc_link_v']:.1f} V | {nominal_qual['maximum_required_dc_link_v']:.1f} V | {worst_qual['maximum_required_dc_link_v']:.1f} V |
| Terminal frequency | {nominal_ref['maximum_terminal_frequency_hz']:.1f} Hz | {nominal_qual['maximum_terminal_frequency_hz']:.1f} Hz | {worst_qual['maximum_terminal_frequency_hz']:.1f} Hz |
| Worst cage rise | {nominal_ref['maximum_cage_copper_rise_k']:.1f} K | {nominal_qual['maximum_cage_copper_rise_k']:.1f} K | {worst_qual['maximum_cage_copper_rise_k']:.1f} K |

The worst selected corner is 0.25 mm clearance per side, 90% cage conductance and 150% stationary
core H. It still passes every band. Its reference source energy is
{worst_ref['maximum_source_energy_j']:.1f} J and its qualification source energy is
{worst_qual['maximum_source_energy_j']:.1f} J.

## What I changed after the first A3f pass

| Quantity | A3f first pass | A3g nominal selection |
|---|---:|---:|
| Pitch / wavelength | 16 / 48 mm | 30 / 90 mm |
| Equivalent field | 0.62 T | 0.56 T |
| Active primary mass | {a3f['active_primary_mass']['total_kg']:.2f} kg | {design['active_primary_mass_kg']:.2f} kg |
| Reference source energy | {a3f_ref['source_energy_j']:.1f} J | {nominal_ref['maximum_source_energy_j']:.1f} J |
| Qualification source energy | {a3f_qual['source_energy_j']:.1f} J | {nominal_qual['maximum_source_energy_j']:.1f} J |
| Source-to-payload efficiency | {100 * a3f_qual['source_to_payload_efficiency']:.1f}% | {100 * nominal_qual['minimum_source_to_payload_efficiency']:.1f}% |

My selected primary is {design['active_primary_mass_kg'] - a3f['active_primary_mass']['total_kg']:.2f}
kg heavier because the wider slot is deliberately filled with more copper, but nominal qualification
energy falls by **{100 * energy_reduction:.1f}%** and frequency falls by roughly 40%. The trade is
physical: fewer, larger cells buy conductor section, lower resistance and a longer wavelength.

## What I decided next

**{result['disposition'].replace('_', ' ')}.**

The 30 mm / 0.56 T point now controls Gen2 CAD and the first independent field solve. Optimisation
does not close bar homogenization, saturation after perforation, end-turn routing, gap tolerances,
cooling or provider acceptance.

See the immutable [A3g run sheet](../validation/A3g_fluxbridge_optimization.md).
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.write:
        OUTPUT.write_text(rendered, encoding="utf-8")
    elif args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            raise SystemExit("stale generated file: docs/FLUXBRIDGE_OPTIMIZATION.md")
    else:
        print(rendered, end="")


if __name__ == "__main__":
    main()
