"""Render my A7c Gen2.7 selected-point cage/circuit result."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "analysis" / "results" / "gen27_cage_circuit.json"
A8B = ROOT / "analysis" / "results" / "gen27_codesign.json"
OUTPUT = ROOT / "docs" / "GEN27_CAGE_CIRCUIT.md"


def corner_key(record: dict) -> tuple[float, float]:
    corner = record["corner"]
    return (
        corner["cage_sheet_conductance_multiplier"],
        corner["phase_resistance_multiplier"],
    )


def render() -> str:
    result = json.loads(INPUT.read_text(encoding="utf-8"))
    a8b = json.loads(A8B.read_text(encoding="utf-8"))["selected_candidate"]
    corners = result["corners"]
    hot = next(corner for corner in corners if corner_key(corner) == (0.9, 1.25))
    old_hot = next(corner for corner in a8b["corners"] if corner_key(corner) == (0.9, 1.25))
    worst_reference = max(corner["reference"]["maximum_source_energy_j"] for corner in corners)
    worst_qualification = max(
        corner["qualification"]["maximum_source_energy_j"] for corner in corners
    )
    minimum_source_efficiency = min(
        corner[case]["minimum_source_to_payload_efficiency"]
        for corner in corners
        for case in ("reference", "qualification")
    )
    minimum_secondary_efficiency = min(
        corner[case]["minimum_secondary_only_efficiency"]
        for corner in corners
        for case in ("reference", "qualification")
    )
    worst_cage_rise = max(
        corner[case]["maximum_cage_copper_rise_k"]
        for corner in corners
        for case in ("reference", "qualification")
    )
    worst_current = max(
        corner[case]["maximum_cage_current_density_a_m2"]
        for corner in corners
        for case in ("reference", "qualification")
    )
    worst_slip = max(
        corner[case]["maximum_cage_slip_m_s"]
        for corner in corners
        for case in ("reference", "qualification")
    )
    worst_power = max(
        corner[case]["maximum_peak_dc_power_w"]
        for corner in corners
        for case in ("reference", "qualification")
    )
    worst_primary_rise = max(
        corner[case]["maximum_primary_copper_rise_k"]
        for corner in corners
        for case in ("reference", "qualification")
    )
    worst_frequency = max(
        corner[case]["maximum_terminal_frequency_hz"]
        for corner in corners
        for case in ("reference", "qualification")
    )
    worst_voltage = max(corner["maximum_required_dc_link_v"] for corner in corners)
    worst_normal = max(corner["unbalanced_normal_force_n"] for corner in corners)
    passing_corners = sum(corner["pass"] for corner in corners)
    reference_margin = 900.0 - worst_reference
    reference_margin_fraction = reference_margin / 900.0
    energy_delta = (
        hot["reference"]["maximum_source_energy_j"]
        - old_hot["reference"]["maximum_source_energy_j"]
    )
    field_change_percent = 100 * (
        result["field_trace"]["equivalent_sheet_field_rms_t"]
        / a8b["design"]["equivalent_field_rms_t"]
        - 1
    )
    inductance_drop_percent = 100 * (
        1
        - result["field_trace"]["fine_active_window_phase_inductance_h"]
        / a8b["sectional"]["phase_inductance_h"]
    )

    return f"""# A7c selected Gen2.7 Fluxrelay cage/circuit reclosure

> **Generated by `tools/make_gen27_cage_circuit.py`. Do not hand-edit.**  
> Evidence class: **POST-FIELD HOMOGENIZED CAGE + LUMPED SECTIONAL CIRCUIT/CG SHOT MODEL**.  
> I do not present this as switching, transient force, structural or hardware evidence.

## What I found

**I found {passing_corners}/4 robustness corners passing all {result['band_count']} frozen hard
bands.** I made no post-run change to the selected point, model, corners or thresholds.

| Quantity | Worst A7c result | Frozen band | Outcome |
|---|---:|---:|---:|
| Reference source energy | {worst_reference:.3f} J | <=900 J | PASS |
| Reference energy margin | {reference_margin:.3f} J ({100 * reference_margin_fraction:.3f}%) | >0 J | PASS |
| Qualification source energy | {worst_qualification:.3f} J | <=1,500 J | PASS |
| Source-to-payload efficiency | {100 * minimum_source_efficiency:.3f}% | >=30% | PASS |
| Secondary-only efficiency | {100 * minimum_secondary_efficiency:.3f}% | >=50% | PASS |
| Cage copper rise | {worst_cage_rise:.3f} K | <=20 K | PASS |
| Cage current density | {worst_current / 1e6:.3f} A/mm2 | <=180 A/mm2 | PASS |
| Cage slip | {worst_slip:.3f} m/s | <=8 m/s | PASS |
| Required DC link | {worst_voltage:.3f} V | <=48 V and >=10% margin | PASS |
| Peak DC power | {worst_power / 1e3:.3f} kW | <=15 kW | PASS |
| Primary copper rise | {worst_primary_rise:.3f} K | <=3 K | PASS |
| Terminal frequency | {worst_frequency:.3f} Hz | <=350 Hz | PASS |
| Unbalanced normal force | {worst_normal:.3f} N | <=100 N | PASS |

## What changed from my A8b surrogate

My fresh equivalent-sheet field is {result['field_trace']['equivalent_sheet_field_rms_t']:.6f} T,
up {field_change_percent:.3f}% from A8b. My solved active-window inductance is
{1e6 * result['field_trace']['fine_active_window_phase_inductance_h']:.5f} uH, down
{inductance_drop_percent:.3f}%. At the controlling 90%-conductance / 125%-resistance corner, my
reclosure changes reference energy by {energy_delta:+.3f} J to
{hot['reference']['maximum_source_energy_j']:.3f} J.

The point passes, but I have only {reference_margin:.3f} J of model margin on the controlling
reference shot. I will not round that into a comfortable result or treat the arbitrary 125%
resistance corner as supplier-backed winding evidence.

## What I decided next

I promoted the exact selected point to provisional A5e Gen3 CAD and an A9 transient sectional-drive
gate. Gen3 must account for structure, containment, insulation, cooling, wiring and real winding
length without hiding them inside my 92 g active-material margin. A9 must resolve cell handoff,
current rise, force ripple, failed-cell behavior and exit timing.

I retain the complete {result['cg_point_artifact']['record_count']:,}-point table in
`{result['cg_point_artifact']['path']}`.

![A7c qualification cage-rise map](../analysis/figures/a7c/A7c_qualification_cage_rise_map.png)

![A7c controlling margins](../analysis/figures/a7c/A7c_controlling_margins.png)

![A7c fresh-field reclosure deltas](../analysis/figures/a7c/A7c_surrogate_reclosure_delta.png)

See my immutable [A7c run sheet](../validation/A7c_gen27_cage_circuit.md).
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.write:
        OUTPUT.write_text(content, encoding="utf-8")
    elif args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            raise SystemExit("stale generated file: docs/GEN27_CAGE_CIRCUIT.md")
    else:
        print(content, end="")


if __name__ == "__main__":
    main()
