"""Render the A5a comb-fin envelope summary from its committed JSON result."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "analysis" / "results" / "interface_fit_screen.json"
OUTPUT = ROOT / "docs" / "INTERFACE_FIT_SCREEN.md"


def render() -> str:
    with INPUT.open(encoding="utf-8") as handle:
        result = json.load(handle)
    geometry = result["geometry"]
    mass = result["moving_mass"]
    allocation = result["force_allocation"]
    failed = [name.replace("_", " ") for name, passed in result["bands"].items() if not passed]
    failed_text = ", ".join(failed) if failed else "none"
    return f"""# A5a comb-fin envelope screen

> **Generated by `tools/make_interface_fit_screen.py`. Do not hand-edit.**  
> Evidence class: **ANALYTICAL MODEL OUTPUT checked against named EXTERNAL GUIDANCE**. This is
> not dispenser acceptance, FEA or measurement.

## What I found

The three-fin comb preserves **{geometry['active_area_m2_per_channel'] * 1e4:.2f} cm²** developed
air-gap area per channel while projecting **{geometry['total_projection_from_rail_plane_m'] * 1e3:.2f} mm**
from the rail plane. Its stationary three-slot/four-web footprint is
**{geometry['stationary_comb_span_m'] * 1e3:.2f} mm**, centred between the corner-rail keep-outs.

| Quantity | Result |
|---|---:|
| Edge-to-comb clearance | {geometry['rail_edge_to_comb_clearance_m'] * 1e3:.2f} mm |
| Usable side-face width | {geometry['usable_face_width_between_rail_keepouts_m'] * 1e3:.2f} mm |
| Projected usable-face fraction | {100 * geometry['projected_usable_face_fraction']:.1f}% |
| Effective magnetic gap per side | {geometry['nominal_effective_gap_per_side_m'] * 1e3:.2f} mm |
| Segmented steel mass | {mass['segmented_steel_kg'] * 1e3:.1f} g |
| Aluminium side/tip cover mass | {mass['side_and_tip_cover_kg'] * 1e3:.1f} g |
| Root/capture/fastener allowance | {mass['root_capture_fastener_allowance_kg'] * 1e3:.1f} g |
| Total interface increment | {mass['interface_increment_kg'] * 1e3:.1f} g |

The face-centred allocation closes every one of the **{allocation['grid_point_count']}** frozen CG
points. Peak channel force is **{allocation['maximum_channel_force_n']:.2f} N**
({100 * allocation['maximum_channel_fraction']:.2f}% of total), and required developed shear is
**{allocation['required_developed_shear_pa'] / 1000:.2f} kPa**.

## What I found against my declared bands

**{result['band_pass_count']}/{result['band_count']} A5a bands pass.** Failed bands: {failed_text}.

Disposition: **{result['disposition'].replace('_', ' ')}**.

## How I interpret it

I read this result as evidence that a low-profile three-fin cross-section can be drawn inside the selected preliminary
guidance while retaining four positive force channels and the A3 force area. It does not say an
existing dispenser contains the needed stator volume, that the fin roots survive launch, or that
the machine produces thrust.

Next, this exact cross-section—not the rejected corner return—must receive nonlinear 2D/3D
electromagnetic analysis and a selected-provider drawing review. The induction lane remains the
fallback if either gate fails.

See the [dimensioned comb-fin drawing](../cad/a5a_comb_fin_cross_section.svg) and immutable
[A5a run sheet](../validation/A5a_comb_fin_envelope.md).
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.write:
        OUTPUT.write_text(rendered, encoding="utf-8")
    elif args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            raise SystemExit("stale generated file: docs/INTERFACE_FIT_SCREEN.md")
    else:
        print(rendered, end="")


if __name__ == "__main__":
    main()

