"""Render the A5b quad-comb screen from its committed JSON result."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "analysis" / "results" / "quad_comb_screen.json"
OUTPUT = ROOT / "docs" / "QUAD_COMB_SCREEN.md"


def render() -> str:
    with INPUT.open(encoding="utf-8") as handle:
        result = json.load(handle)
    geometry = result["geometry"]
    mass = result["moving_mass"]
    allocation = result["force_allocation"]
    force = result["ideal_edge_force_bound"]
    failed = [name.replace("_", " ") for name, passed in result["bands"].items() if not passed]
    failed_text = ", ".join(failed) if failed else "none"
    return f"""# A5b quad-comb screen

> **Generated by `tools/make_quad_comb_screen.py`. Do not hand-edit.**  
> Evidence class: **ANALYTICAL MODEL OUTPUT checked against named EXTERNAL GUIDANCE/MATERIAL
> DATA**. This is not provider acceptance, nonlinear FEA or measurement.

## Outcome

The redesigned face channel uses **{geometry['fins_per_channel']} aligned fins**, each
**{geometry['active_fin_height_m'] * 1e3:.1f} mm** high, for
**{geometry['active_edge_count_per_channel']}** ideal simultaneously active overlap edges.

| Quantity | Result |
|---|---:|
| Total projection from rail plane | {geometry['total_projection_from_rail_plane_m'] * 1e3:.2f} mm |
| Nominal protrusion reserve | {geometry['nominal_protrusion_margin_m'] * 1e3:.2f} mm |
| Stationary slot/web footprint | {geometry['stationary_comb_span_m'] * 1e3:.2f} mm |
| Projected usable-face fraction | {100 * geometry['projected_usable_face_fraction']:.1f}% |
| Effective gap per side | {geometry['nominal_effective_gap_per_side_m'] * 1e3:.2f} mm |
| Segmented steel mass | {mass['segmented_steel_kg'] * 1e3:.1f} g |
| Aluminium side/tip cover mass | {mass['side_and_tip_cover_kg'] * 1e3:.1f} g |
| Root/capture/fastener allowance | {mass['root_capture_fastener_allowance_kg'] * 1e3:.1f} g |
| Total interface increment | {mass['interface_increment_kg'] * 1e3:.1f} g |
| Peak channel force over {allocation['grid_point_count']} CG points | {allocation['maximum_channel_force_n']:.2f} N |
| Required ideal flux density | {force['required_ideal_flux_density_t']:.3f} T |
| Ideal force at {force['design_flux_density_t']:.1f} T | {force['ideal_force_at_design_field_n']:.2f} N |
| Ideal margin at {force['design_flux_density_t']:.1f} T | {100 * force['ideal_force_margin_fraction_at_design_field']:.1f}% |

## Declared-band result

**{result['band_pass_count']}/{result['band_count']} A5b bands pass.** Failed bands: {failed_text}.

Disposition: **{result['disposition'].replace('_', ' ')}**.

## Interpretation

The small payload modification recovers the force-bound margin that the three-fin comb lacked:
one additional passive fin per face and 1.0 mm more active height. The fins remain axially aligned
so all 28 ideal overlap edges can contribute together; force phasing belongs in the launcher
stator, not in the spacecraft geometry.

A pass only chooses the geometry for A3b1. The next model must define an actual three-dimensional
return yoke, coil window and phase layout, use a selected nonlinear B-H curve, and solve force,
normal load, current, voltage, loss and heating across the 150 ms shot.

See the immutable [A5b run sheet](../validation/A5b_quad_comb_envelope.md), the preceding
[A3b0 rejection](EDGE_FORCE_BOUND.md), and the [design decision](adr/006-edge-bound-redesign.md).
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.write:
        OUTPUT.write_text(rendered, encoding="utf-8")
    elif args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            raise SystemExit("stale generated file: docs/QUAD_COMB_SCREEN.md")
    else:
        print(rendered, end="")


if __name__ == "__main__":
    main()
