"""Render the A3d revised Fluxfoil operating point."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "analysis" / "results" / "induction_operating_point.json"
OUTPUT = ROOT / "docs" / "INDUCTION_OPERATING_POINT.md"


def render() -> str:
    with INPUT.open(encoding="utf-8") as handle:
        result = json.load(handle)
    rated = result["rated_channel"]
    shot = result["qualification_shot"]
    worst = shot["worst_secondary_heat_point"]
    failed = [name.replace("_", " ") for name, passed in result["bands"].items() if not passed]
    failed_text = ", ".join(failed) if failed else "none"
    return f"""# A3d Fluxfoil operating point

> **Generated by `tools/make_induction_operating_point.py`. Do not hand-edit.**  
> Evidence class: **REVISED ANALYTICAL OPERATING-POINT OUTPUT** after A3c's frozen efficiency
> miss. I do not present this as field FEA, a stator design or measurement.

## What I found

A3d changes one launcher-side input and no spacecraft geometry: external travelling field rises
from 0.50 to **0.60 T RMS**.

| Quantity | A3c, 0.50 T | A3d, 0.60 T |
|---|---:|---:|
| Rated slip speed | 3.590 m/s | {rated['slip_speed_m_s']:.3f} m/s |
| RMS conductor current density | 63.4 MA/m² | {rated['current_density_rms_a_m2'] / 1e6:.1f} MA/m² |
| Rated local adiabatic rise | 7.01 K | {rated['adiabatic_temperature_rise_k']:.2f} K |
| Start-to-terminal frequency | 74.8–322.4 Hz | {rated['start_electrical_frequency_hz']:.1f}–{rated['terminal_electrical_frequency_hz']:.1f} Hz |
| Worst-CG secondary-only efficiency | 66.2% | {100 * worst['secondary_only_shot_efficiency']:.1f}% |
| Worst-CG peak air-gap power | 7.29 kW | {worst['peak_airgap_power_w'] / 1000:.2f} kW |
| Normal force per side | 797 N | {rated['normal_force_per_side_n']:.0f} N |
| Residual at 1% field mismatch | 15.9 N | {rated['unbalanced_normal_force_n']:.1f} N |

## What I found against my declared bands

**{result['band_pass_count']}/{result['band_count']} A3d bands pass.** Failed bands: {failed_text}.

Disposition: **{result['disposition'].replace('_', ' ')}**.

The field increase is not free: symmetric normal preload grows and the launcher must now create
0.60 T over the complete chirp. That becomes the next explicit stator/circuit gate. The A3c
failure remains the record of why 0.50 T is not the baseline.

See the immutable [A3d run sheet](../validation/A3d_fluxfoil_operating_point.md).
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.write:
        OUTPUT.write_text(rendered, encoding="utf-8")
    elif args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            raise SystemExit("stale generated file: docs/INDUCTION_OPERATING_POINT.md")
    else:
        print(rendered, end="")


if __name__ == "__main__":
    main()
