"""Render the single authoritative numeric baseline from committed JSON results."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "BASELINE.md"


def load(name: str) -> dict:
    with (ROOT / "analysis" / "results" / name).open(encoding="utf-8") as handle:
        return json.load(handle)


def render() -> str:
    b = load("baseline.json")
    f = load("force_allocation.json")
    t = load("architecture_trade.json")
    ref = b["reference_case"]
    qual = b["qualification_case"]
    interface = b["interface"]
    topology_path = ROOT / "analysis" / "results" / "topology_screen.json"
    topology_complete = topology_path.exists()
    rows = []
    for name, item in t["candidates"].items():
        display_name = name.replace("_", " ")
        if topology_complete and name == "Bolley_R_baseline":
            display_name = "Bolley R A1 equivalent-thickness placeholder"
        rows.append(
            f"| {display_name} | {item['launcher_moving_mass_kg']:.3f} | "
            f"{100*item['payload_mass_fraction']:.1f}% | {item['total_mechanical_energy_j']:.1f} |"
        )
    passed = sum(bool(value) for value in b["bands"].values()) + sum(
        bool(value) for value in f["bands"].values()
    )
    total = len(b["bands"]) + len(f["bands"])
    topology_warning = ""
    if topology_complete:
        topology_warning = """> **A3a correction:** the 0.229 kg value below is the frozen A1 equivalent-thickness
> placeholder, not a physically closed flux-path rail. Do not quote it as a designed interface
> mass. See [`TOPOLOGY_SCREEN.md`](TOPOLOGY_SCREEN.md)."""
    return f"""# Frozen Phase 0 baseline

> **Generated by `tools/make_baseline.py`. Do not hand-edit.**  
> Evidence class: **MODEL OUTPUT from ASSUMPTION inputs**. Nothing here is a measurement.
{topology_warning}

## Reference shot

| Quantity | Value |
|---|---:|
| Payload | {b['inputs']['reference_payload_kg']:.3f} kg 3U |
| Screened cooperative-interface increment | {interface['screened_incremental_mass_kg']:.3f} kg |
| Powered length | {b['inputs']['powered_length_m']:.3f} m |
| Acceleration | {b['inputs']['acceleration_g']:.2f} g |
| Ideal exit velocity | {ref['exit_velocity_m_s']:.3f} m/s |
| Total axial force | {ref['total_force_n']:.1f} N |
| Payload kinetic energy | {ref['payload_ke_j']:.1f} J |
| Total moving kinetic energy | {ref['total_moving_ke_j']:.1f} J |
| Mechanical utilisation | {100*ref['mechanical_utilisation_fraction']:.2f}% |
| Gross energy screen, 40–60% efficiency | {ref['gross_energy_screen_j_at_60pct']:.0f}–{ref['gross_energy_screen_j_at_40pct']:.0f} J |
| Peak mechanical power | {ref['peak_mechanical_power_w']/1000:.2f} kW |
| Pole-passage frequency | {ref['pole_passage_hz']:.1f} Hz |

## Six-kilogram qualification sizing case

| Quantity | Value |
|---|---:|
| Total force | {qual['total_force_n']:.1f} N |
| Worst-corner force at double CG limit | {qual['worst_corner_force_n']:.1f} N |
| Required worst-corner shear | {qual['required_worst_corner_shear_pa']/1000:.2f} kPa |
| External published benchmark | {qual['published_shear_benchmark_pa']/1000:.2f} kPa |
| Screened margin to benchmark | {100*qual['benchmark_margin_fraction']:.1f}% |
| Maximum allocation fraction | {100*f['maximum_channel_fraction']:.2f}% |
| Minimum commanded channel force | {f['minimum_channel_force_n']:.1f} N |

The published shear number is external evidence from another machine. The margin is a reason to
run FEA and build a coupon, not evidence that this covered hybrid rail will work.

## Common-duty moving-mass comparison

| Architecture | Non-payload moving mass, kg | Payload fraction | Mechanical energy, J |
|---|---:|---:|---:|
{chr(10).join(rows)}

Electrical efficiency is intentionally absent from this comparison.

## Declared-band result

**{passed}/{total} first-order bands pass.** Passing means the architecture survives its initial
dimensional and algebraic screens. A3 commutation and force production remain the first physical
kill tests.

## Frozen caveats

- No flux-linkage, saturation, voltage, current, thermal or normal-force model exists.
- The 40–60% efficiency range is an assumption.
- No supplier component has been selected.
- No launch provider has accepted the hybrid rail.
- No hardware has been built.
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.write:
        OUTPUT.write_text(rendered, encoding="utf-8")
    elif args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            raise SystemExit("stale generated file: docs/BASELINE.md")
    else:
        print(rendered, end="")


if __name__ == "__main__":
    main()
