"""Render the A6c Gen2.2 Fluxmanifold-R4 nonlinear field result."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "analysis" / "results" / "gen22_field.json"
OUTPUT = ROOT / "docs" / "GEN22_FIELD.md"


def mark(value: bool) -> str:
    return "PASS" if value else "**FAIL**"


def render() -> str:
    r = json.loads(INPUT.read_text(encoding="utf-8"))
    f = r["mesh_results"]["fine"]
    c = r["convergence"]
    b = r["bands"]
    x = r["physics_band_extrema"]
    failed = ", ".join(name.replace("_", " ") for name in r["failed_bands"])
    return f"""# A6c Gen2.2 Fluxmanifold-R4 field gate

> **Generated by `tools/make_gen22_field.py`. Do not hand-edit.**  
> Evidence class: **THREE-MESH 2D NONLINEAR RMS-EQUIVALENT MAGNETOSTATIC FEA**.
> Physical bands use the worst of all three meshes. This is not measured field or force.

## Result

**{r['band_pass_count']}/{r['band_count']} declared bands pass.** Failed band: {failed}.

| Quantity | Controlled result | Frozen band | Outcome |
|---|---:|---:|---:|
| Base-to-fine mean-field change | {100*c['base_to_fine_mean_slot_field_change_fraction']:.3f}% | <=2.000% | {mark(b['mesh_mean_field_convergence'])} |
| Base-to-fine coenergy change | {100*c['base_to_fine_coenergy_change_fraction']:.3f}% | <=4.000% | {mark(b['mesh_coenergy_convergence'])} |
| Expanded-boundary mean-field change | {100*c['base_to_expanded_boundary_mean_slot_field_change_fraction']:.3f}% | <=2.000% | {mark(b['outer_boundary_sensitivity'])} |
| Worst-mesh mean-field range | {x['minimum_mean_tooth_slice_field_rms_t']:.4f}–{x['maximum_mean_tooth_slice_field_rms_t']:.4f} T | 0.7200–0.8600 T | {mark(b['mean_field_lower'] and b['mean_field_upper'])} |
| Worst slot-flux imbalance | {100*x['maximum_slot_to_slot_flux_imbalance_fraction']:.3f}% | <=5.000% | {mark(b['slot_flux_balance'])} |
| Worst active-height field CV | {100*x['maximum_active_height_field_coefficient_of_variation']:.3f}% | <=15.000% | {mark(b['active_height_field_uniformity'])} |
| Worst inferred ligament peak | {x['maximum_inferred_magnetic_ligament_field_t']:.4f} T | <=1.4500 T | {mark(b['magnetic_ligament_field'])} |
| Worst stationary-core peak | {x['maximum_stationary_core_field_t']:.4f} T | <=1.5500 T | {mark(b['stationary_core_field'])} |
| Fine per-cell inductance ratio to A3g | {r['fine_inductance_ratio_to_a3g']:.4f} | 0.6800–1.0500 | {mark(b['inductance_lower'] and b['inductance_upper'])} |
| Worst source-current residual | {x['maximum_source_current_residual_fraction']:.3e} | <=1.000e-10 | {mark(b['source_current_closure'])} |
| Worst final nonlinear solution change | {x['maximum_nonlinear_relative_solution_change']:.3e} | <=1.000e-4 | {mark(b['nonlinear_convergence'])} |

## Disposition

Fluxmanifold-R4 fixes the launcher return: worst stationary peak is
{x['maximum_stationary_core_field_t']:.4f} T, with fine core p99 only
{f['stationary_core_field_p99_t']:.4f} T. Field, balance, uniformity, inductance and every
numerical check pass. The single failure is the moving rib at
{x['maximum_inferred_magnetic_ligament_field_t']:.4f} T.

**{r['disposition'].replace('_', ' ')}.** Gen2.2 is not promoted. Gen2.3 must add passive magnetic
cross-section without shrinking the copper rung duty, then rerun this same worst-mesh gate.

![A6c fine field](../analysis/figures/a6c/A6c_field_magnitude.png)

![A6c blade distribution](../analysis/figures/a6c/A6c_blade_fields.png)

![A6c convergence](../analysis/figures/a6c/A6c_convergence.png)

See the immutable [A6c run sheet](../validation/A6c_gen22_fluxmanifold_r4.md).
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.write:
        OUTPUT.write_text(content, encoding="utf-8")
    elif args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            raise SystemExit("stale generated file: docs/GEN22_FIELD.md")
    else:
        print(content, end="")


if __name__ == "__main__":
    main()
