"""Render the A6d Gen2.3 Fluxrib nonlinear field result."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "analysis" / "results" / "gen23_field.json"
OUTPUT = ROOT / "docs" / "GEN23_FIELD.md"


def mark(value: bool) -> str:
    return "PASS" if value else "**FAIL**"


def render() -> str:
    r = json.loads(INPUT.read_text(encoding="utf-8"))
    x = r["physics_band_extrema"]
    b = r["bands"]
    c = r["convergence"]
    return f"""# A6d Gen2.3 Fluxrib field gate

> **Generated by `tools/make_gen23_field.py`. Do not hand-edit.**  
> Evidence class: **THREE-MESH 2D NONLINEAR RMS-EQUIVALENT MAGNETOSTATIC FEA**.
> Physical bands use the worst of all three meshes. This is not measurement or force evidence.

## Result

**{r['band_pass_count']}/{r['band_count']} declared bands pass.** Failed band: magnetic ligament
field.

| Quantity | Controlled result | Frozen band | Outcome |
|---|---:|---:|---:|
| Base-to-fine mean-field change | {100*c['base_to_fine_mean_slot_field_change_fraction']:.3f}% | <=2.000% | {mark(b['mesh_mean_field_convergence'])} |
| Base-to-fine coenergy change | {100*c['base_to_fine_coenergy_change_fraction']:.3f}% | <=4.000% | {mark(b['mesh_coenergy_convergence'])} |
| Boundary mean-field change | {100*c['base_to_expanded_boundary_mean_slot_field_change_fraction']:.3f}% | <=2.000% | {mark(b['outer_boundary_sensitivity'])} |
| Worst-mesh mean-field range | {x['minimum_mean_tooth_slice_field_rms_t']:.4f}–{x['maximum_mean_tooth_slice_field_rms_t']:.4f} T | 0.7200–0.8600 T | {mark(b['mean_field_lower'] and b['mean_field_upper'])} |
| Worst slot imbalance / height CV | {100*x['maximum_slot_to_slot_flux_imbalance_fraction']:.3f}% / {100*x['maximum_active_height_field_coefficient_of_variation']:.3f}% | <=5% / <=15% | {mark(b['slot_flux_balance'] and b['active_height_field_uniformity'])} |
| Worst inferred ligament peak | {x['maximum_inferred_magnetic_ligament_field_t']:.4f} T | <=1.4500 T | {mark(b['magnetic_ligament_field'])} |
| Worst stationary-core peak | {x['maximum_stationary_core_field_t']:.4f} T | <=1.5500 T | {mark(b['stationary_core_field'])} |
| Fine inductance ratio to A3g | {r['fine_inductance_ratio_to_a3g']:.4f} | 0.6800–1.0500 | {mark(b['inductance_lower'] and b['inductance_upper'])} |
| Worst source / nonlinear closure | {x['maximum_source_current_residual_fraction']:.3e} / {x['maximum_nonlinear_relative_solution_change']:.3e} | <=1e-10 / <=1e-4 | {mark(b['source_current_closure'] and b['nonlinear_convergence'])} |

The 14.23 g rib thickening reduces the worst ligament estimate from A6c's 1.5306 T to
{x['maximum_inferred_magnetic_ligament_field_t']:.4f} T, but that remains
{100*(x['maximum_inferred_magnetic_ligament_field_t']/1.45-1):.2f}% above the frozen limit.
Everything else passes, including the field floor and the R4 return.

## Disposition

**{r['disposition'].replace('_', ' ')}.** A6d remains failed. The next rib may exceed the old
0.30 kg preferred interface mass, but must remain below the unchanged 0.40 kg absolute limit and
must keep copper rung geometry intact.

![A6d fine field](../analysis/figures/a6d/A6d_field_magnitude.png)

![A6d blade distribution](../analysis/figures/a6d/A6d_blade_fields.png)

![A6d convergence](../analysis/figures/a6d/A6d_convergence.png)

See the immutable [A6d run sheet](../validation/A6d_gen23_fluxrib.md).
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.write:
        OUTPUT.write_text(content, encoding="utf-8")
    elif args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            raise SystemExit("stale generated file: docs/GEN23_FIELD.md")
    else:
        print(content, end="")


if __name__ == "__main__":
    main()
