"""Render my A12 Fluxframe mass-envelope result."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "analysis" / "results" / "fluxframe_mass.json"
OUTPUT = ROOT / "docs" / "FLUXFRAME_MASS.md"


def render() -> str:
    result = json.loads(INPUT.read_text(encoding="utf-8"))
    rows = []
    for item in result["comparators"]:
        rows.append(
            f"| `{item['id']}` | {1000*item['mass_kg']:.0f} g | {item['mass_semantics'].lower().replace('_', ' ')} | "
            f"{100*item['required_replacement_fraction']:.2f}% | "
            f"{1000*item['hypothetical_full_replacement_net_added_mass_kg']:.2f} g |"
        )
    check_rows = []
    for check in result["checks"]:
        value = check["value"]
        shown = "no evidence" if value is None else f"{value:.6g}" if isinstance(value, float) else str(value)
        check_rows.append(f"| {check['id']}. {check['name']} | {shown} | **{check['status']}** |")
    return f"""# A12 Fluxframe public chassis-mass screen

> **Generated by `tools/make_fluxframe_mass.py`. Do not hand-edit.**  
> Evidence class: **SOURCED PUBLIC MASS ENVELOPE**. I grant zero displaced-mass credit and make no
> structural, thermal, electrical, magnetic or provider-compatibility claim.

## What I found

My five executable frozen bands pass; three integration bands remain OPEN.

| Band | Result | Status |
|---|---:|---|
{chr(10).join(check_rows)}

I need **{1000*result['required_displaced_mass_kg']:.2f} g** of real removed bus hardware for the
0.37136 kg interface to meet my 0.25 kg net-added preference.

| Public 3U comparator | Published mass | Semantics I preserve | Fraction needed | Net addition if fully replaced |
|---|---:|---|---:|---:|
{chr(10).join(rows)}

The arithmetic says the target is material but not absurd: it is 30.80–42.58% of the published
chassis values I froze. A hypothetical full replacement would put the current interface between a
22.64 g net saving and an 86.36 g net addition across those values.

That sentence is not a design result. The EnduroSat number is an upper bound, so its actual
replaceable mass may be lower. More importantly, Fluxrelay's cage is not currently a primary
spacecraft frame. I have shown only that enough gross structural mass exists in public 3U examples
to justify selecting one bus and attempting the integration.

## My disposition

I promote Gen5 to one selected bus, one before/after parts ledger and one coupled Fluxframe
cross-section. I award **0 g** credit today. CAD promotion requires the same part to preserve CDS
rail/contact geometry, carry ascent and pressure/deployment loads, spread heat, maintain electrical
continuity and remain magnetically acceptable.

See my immutable [A12 run sheet](../validation/A12_fluxframe_mass.md) and
[Gen5 definition](GENERATIONS.md).
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.write:
        OUTPUT.write_text(rendered, encoding="utf-8")
    elif args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            raise SystemExit("stale generated file: docs/FLUXFRAME_MASS.md")
    else:
        print(rendered, end="")


if __name__ == "__main__":
    main()
