"""Render my A6h Gen2.7 Fluxrelay nonlinear field result."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "analysis" / "results" / "gen27_field.json"
A8B = ROOT / "analysis" / "results" / "gen27_codesign.json"
OUTPUT = ROOT / "docs" / "GEN27_FIELD.md"


def mark(value: bool) -> str:
    return "PASS" if value else "**FAIL**"


def render() -> str:
    result = json.loads(INPUT.read_text(encoding="utf-8"))
    a8b = json.loads(A8B.read_text(encoding="utf-8"))["selected_candidate"]
    extrema = result["physics_band_extrema"]
    convergence = result["convergence"]
    bands = result["bands"]
    sectional = result["sectional_drive"]
    field_surrogate = a8b["field_surrogate"]

    solved_stationary = extrema["maximum_stationary_core_field_t"]
    solved_moving = extrema["maximum_inferred_magnetic_ligament_field_t"]
    stationary_delta_mt = 1e3 * (
        solved_stationary - field_surrogate["predicted_stationary_core_peak_t"]
    )
    moving_delta_mt = 1e3 * (
        solved_moving - field_surrogate["predicted_moving_material_peak_t"]
    )

    return f"""# A6h selected Gen2.7 Fluxrelay field gate

> **Generated by `tools/make_gen27_field.py`. Do not hand-edit.**  
> Evidence class: **THREE-MESH 2D NONLINEAR RMS-EQUIVALENT MAGNETOSTATIC FEA**.  
> I use the worst physical value from all three meshes. I do not present this as transient force,
> axial-end, switching or hardware evidence.

## What I found

**I found {result['band_pass_count']}/{result['band_count']} frozen bands passing at the exact A8b
point.** I made no post-run change to the geometry, excitation, mesh, material assumptions or
acceptance bands.

| Quantity | A6h controlled result | Frozen band | Outcome |
|---|---:|---:|---:|
| Base-to-fine mean-field change | {100 * convergence['base_to_fine_mean_slot_field_change_fraction']:.3f}% | <=2.000% | {mark(bands['mesh_mean_field_convergence'])} |
| Base-to-fine coenergy change | {100 * convergence['base_to_fine_coenergy_change_fraction']:.3f}% | <=4.000% | {mark(bands['mesh_coenergy_convergence'])} |
| Expanded-boundary mean-field change | {100 * convergence['base_to_expanded_boundary_mean_slot_field_change_fraction']:.3f}% | <=2.000% | {mark(bands['outer_boundary_sensitivity'])} |
| Worst-mesh mean field | {extrema['minimum_mean_tooth_slice_field_rms_t']:.4f}–{extrema['maximum_mean_tooth_slice_field_rms_t']:.4f} T | 0.7200–0.8600 T | {mark(bands['mean_field_lower'] and bands['mean_field_upper'])} |
| Worst slot imbalance / height CV | {100 * extrema['maximum_slot_to_slot_flux_imbalance_fraction']:.3f}% / {100 * extrema['maximum_active_height_field_coefficient_of_variation']:.3f}% | <=5% / <=15% | {mark(bands['slot_flux_balance'] and bands['active_height_field_uniformity'])} |
| Worst moving-material peak | {solved_moving:.4f} T | <=1.4500 T | {mark(bands['magnetic_ligament_field'])} |
| Worst stationary-core peak | {solved_stationary:.4f} T | <=1.5500 T | {mark(bands['stationary_core_field'])} |
| Fine three-cell phase-window inductance | {1e6 * sectional['fine_active_window_phase_inductance_h']:.5f} uH | 0.85–1.15 x A8b | {mark(bands['active_window_inductance_lower'] and bands['active_window_inductance_upper'])} |
| Inductance ratio to A8b | {sectional['fine_active_window_phase_inductance_ratio_to_a8b']:.5f} | 0.85–1.15 | PASS |
| Worst source / nonlinear closure | {extrema['maximum_source_current_residual_fraction']:.3e} / {extrema['maximum_nonlinear_relative_solution_change']:.3e} | <=1e-10 / <=1e-4 | {mark(bands['source_current_closure'] and bands['nonlinear_convergence'])} |

## What changed from my A8b surrogate

I replaced A8b's current-scaled stationary peak of
{field_surrogate['predicted_stationary_core_peak_t']:.5f} T with a fresh worst-mesh value of
{solved_stationary:.5f} T ({stationary_delta_mt:+.2f} mT). I replaced its predicted moving peak of
{field_surrogate['predicted_moving_material_peak_t']:.5f} T with {solved_moving:.5f} T
({moving_delta_mt:+.2f} mT). The moving peak rose, but it still retains
{100 * (1 - solved_moving / 1.45):.2f}% model margin; the stationary peak retains
{1e3 * (1.55 - solved_stationary):.2f} mT.

I also replaced A8b's {1e6 * result['targets']['a8b_active_window_phase_inductance_h']:.5f} uH
three-cell phase-window surrogate with {1e6 * sectional['fine_active_window_phase_inductance_h']:.5f}
uH from the fine nonlinear mesh. I will carry the solved value into A7c without refitting the
selected geometry or its energy bands.

## What I decided next

I promoted the exact A8b point to A7c selected-point cage/circuit reclosure and provisional Gen3
CAD. I have not validated force, axial end fields, cell handoff, inverter partitioning, structure,
thermal hardware or release performance. A7c remains the next physics gate, and packaged Gen3 mass
can still make me reject Fluxrelay.

![A6h fine field](../analysis/figures/a6h/A6h_field_magnitude.png)

![A6h blade distribution](../analysis/figures/a6h/A6h_blade_fields.png)

![A6h convergence](../analysis/figures/a6h/A6h_convergence.png)

See my immutable [A6h run sheet](../validation/A6h_gen27_fluxrelay.md).
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.write:
        OUTPUT.write_text(content, encoding="utf-8")
    elif args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            raise SystemExit("stale generated file: docs/GEN27_FIELD.md")
    else:
        print(content, end="")


if __name__ == "__main__":
    main()
