"""Render the A5c Gen1 CAD fit result."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "analysis" / "results" / "cad_fit.json"
OUTPUT = ROOT / "docs" / "CAD_FIT.md"


def render() -> str:
    result = json.loads(INPUT.read_text(encoding="utf-8"))
    g = result["geometry"]
    a = result["artifact_counts"]
    winding = result["winding_pack_discovery"]
    failed = ", ".join(name.replace("_", " ") for name in result["failed_bands"])
    return f"""# A5c Gen1 CAD and fit gate

> **Generated by `tools/make_cad_fit.py`. Do not hand-edit.**  
> Evidence class: **PARAMETRIC CAD MANIFEST + EXACT NOMINAL SOLID INTERSECTION**. I do not present this as a
> tolerance study or manufacturing release.

## What I found

**{result['band_pass_count']}/{result['band_count']} declared bands pass.** Failed band: {failed}.

| Quantity | Result |
|---|---:|
| Payload envelope | {g['payload_envelope_mm'][0]:.1f} × {g['payload_envelope_mm'][1]:.1f} × {g['payload_envelope_mm'][2]:.1f} mm |
| Fluxfoil projection | {g['fluxfoil_projection_mm']:.2f} mm |
| Nominal fin clearance, each side | {g['nominal_slot_clearance_per_side_mm']:.2f} mm |
| Stator face footprint / active length | {g['stator_face_footprint_mm']:.1f} / {g['active_stator_length_mm']:.1f} mm |
| Muzzle opening / frame envelope | {g['muzzle_opening_yz_mm']:.1f} / {g['assembly_frame_yz_mm']:.1f} mm |
| Winding overlap, one / four faces | {g['payload_stator_intersection_per_face_mm3']:.1f} / {g['payload_stator_intersection_all_faces_mm3']:.1f} mm³ |
| STEP / STL / render artifacts | {a['step']} / {a['stl']} / {a['render']} |

## What I found had failed

The four foil blades align in the four magnetic slots with the frozen 0.50 mm nominal clearance.
I located the failure in the winding, not the foil: the Gen1 coil envelope intrudes into the first slot by
{g['payload_stator_intersection_per_face_mm3']:.1f} mm³ per face.

The CAD pass also uncovered a stronger physical contradiction outside the frozen bands. A3e asks
for {winding['turns_per_cell']} turns at {winding['conductor_area_per_turn_mm2']:.1f} mm² each:
{winding['gross_copper_section_required_mm2']:.0f} mm² of bare copper per cell. The 0.5 ×
{winding['modelled_coil_height_mm']:.0f} mm inter-cell section offers only
{winding['available_intercell_section_before_fill_factor_mm2']:.1f} mm² before insulation and fill
factor—a {winding['required_to_available_section_ratio']:.1f}:1 deficit.

## What I decided next

**REJECT GEN1 WINDING PACKAGE AND REVISE THE MAGNETIC INTERFACE.**

The A3e electrical result remains a useful upper-level circuit calculation, but its “promote to
CAD” disposition is superseded for packaging. Bolley will not hide the mismatch with a cosmetic
coil. The next generation must cut magnetomotive force and copper section at the source, then pass
a winding-window gate before field analysis.

![A5c axial interference](../cad/renders/gen1/04_winding_interference.png)

See the immutable [A5c run sheet](../validation/A5c_gen1_cad.md).
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.write:
        OUTPUT.write_text(rendered, encoding="utf-8")
    elif args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            raise SystemExit("stale generated file: docs/CAD_FIT.md")
    else:
        print(rendered, end="")


if __name__ == "__main__":
    main()
