"""Render the A6f Gen2.5 Fluxweb nonlinear field result."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "analysis" / "results" / "gen25_field.json"
PARAMETERS = ROOT / "cad" / "gen25_field_parameters.json"
OUTPUT = ROOT / "docs" / "GEN25_FIELD.md"


def mark(value: bool) -> str:
    return "PASS" if value else "**FAIL**"


def render() -> str:
    r = json.loads(INPUT.read_text(encoding="utf-8"))
    p = json.loads(PARAMETERS.read_text(encoding="utf-8"))
    x = r["physics_band_extrema"]
    b = r["bands"]
    c = r["convergence"]
    interface = p["interface_accounting"]
    return f"""# A6f Gen2.5 Fluxweb field gate

> **Generated by `tools/make_gen25_field.py`. Do not hand-edit.**  
> Evidence class: **THREE-MESH 2D NONLINEAR RMS-EQUIVALENT MAGNETOSTATIC FEA**.
> I evaluate physical bands with the worst of all three meshes. I do not present this as measurement, transient cage or
> force evidence.

## What I found

**{r['band_pass_count']}/{r['band_count']} declared magnetic bands pass.** The separate 0.30 kg
interface preference remains failed as declared.

| Quantity | Controlled result | Frozen band | Outcome |
|---|---:|---:|---:|
| Base-to-fine mean-field change | {100*c['base_to_fine_mean_slot_field_change_fraction']:.3f}% | <=2.000% | {mark(b['mesh_mean_field_convergence'])} |
| Base-to-fine coenergy change | {100*c['base_to_fine_coenergy_change_fraction']:.3f}% | <=4.000% | {mark(b['mesh_coenergy_convergence'])} |
| Boundary mean-field change | {100*c['base_to_expanded_boundary_mean_slot_field_change_fraction']:.3f}% | <=2.000% | {mark(b['outer_boundary_sensitivity'])} |
| Worst-mesh mean-field range | {x['minimum_mean_tooth_slice_field_rms_t']:.4f}–{x['maximum_mean_tooth_slice_field_rms_t']:.4f} T | 0.7200–0.8600 T | {mark(b['mean_field_lower'] and b['mean_field_upper'])} |
| Worst slot imbalance | {100*x['maximum_slot_to_slot_flux_imbalance_fraction']:.3f}% | <=5.000% | {mark(b['slot_flux_balance'])} |
| Worst active-height CV | {100*x['maximum_active_height_field_coefficient_of_variation']:.3f}% | <=15.000% | {mark(b['active_height_field_uniformity'])} |
| Worst inferred magnetic-material peak | {x['maximum_inferred_magnetic_ligament_field_t']:.4f} T | <=1.4500 T | {mark(b['magnetic_ligament_field'])} |
| Worst stationary-core peak | {x['maximum_stationary_core_field_t']:.4f} T | <=1.5500 T | {mark(b['stationary_core_field'])} |
| Fine inductance ratio to A3g | {r['fine_inductance_ratio_to_a3g']:.4f} | 0.6800–1.0500 | {mark(b['inductance_lower'] and b['inductance_upper'])} |
| Worst source residual | {x['maximum_source_current_residual_fraction']:.3e} | <=1e-10 | {mark(b['source_current_closure'])} |
| Worst final nonlinear change | {x['maximum_nonlinear_relative_solution_change']:.3e} | <=1e-4 | {mark(b['nonlinear_convergence'])} |
| Interface increment | {interface['total_interface_increment_kg']:.5f} kg | preferred <=0.30000 kg | **FAIL** |
| Interface increment | {interface['total_interface_increment_kg']:.5f} kg | absolute <=0.40000 kg | PASS |

The 0.20 mm magnetic backstrap closes the failure without another external-width increment. The
worst magnetic-material estimate is {x['maximum_inferred_magnetic_ligament_field_t']:.4f} T,
{100*(1-x['maximum_inferred_magnetic_ligament_field_t']/1.45):.2f}% below its limit. The trade is
real: equivalent cage copper falls to {interface['equivalent_copper_sheet_thickness_mm']:.3f} mm
and the interface preference is missed by {-1000*interface['preferred_interface_margin_kg']:.2f} g.

## What I decided next

**{r['disposition'].replace('_', ' ')}.** This promotes the Fluxweb only to new cage/circuit,
discrete CAD and transient-force gates. It does not validate the layered joint or the machine.

I do not treat this as a loose pass. Base-to-fine mean field changes
{100*c['base_to_fine_mean_slot_field_change_fraction']:.3f}% against 2%, and worst nonlinear
closure is {x['maximum_nonlinear_relative_solution_change']:.3e} against 1e-4. The next field model
must resolve the axial bar/backstrap pattern rather than treating this 2D homogenization as final.

![A6f fine field](../analysis/figures/a6f/A6f_field_magnitude.png)

![A6f blade distribution](../analysis/figures/a6f/A6f_blade_fields.png)

![A6f convergence](../analysis/figures/a6f/A6f_convergence.png)

See the immutable [A6f run sheet](../validation/A6f_gen25_fluxweb.md).
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.write:
        OUTPUT.write_text(content, encoding="utf-8")
    elif args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            raise SystemExit("stale generated file: docs/GEN25_FIELD.md")
    else:
        print(content, end="")


if __name__ == "__main__":
    main()
