"""Render the A7a Gen2.5 cage/circuit result."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "analysis" / "results" / "gen25_cage_circuit.json"
OUTPUT = ROOT / "docs" / "GEN25_CAGE_CIRCUIT.md"


def render() -> str:
    r = json.loads(INPUT.read_text(encoding="utf-8"))
    corners = r["corners"]
    worst_reference_energy = max(c["reference"]["maximum_source_energy_j"] for c in corners)
    worst_qualification_energy = max(c["qualification"]["maximum_source_energy_j"] for c in corners)
    minimum_source_efficiency = min(
        c[case]["minimum_source_to_payload_efficiency"]
        for c in corners
        for case in ("reference", "qualification")
    )
    minimum_secondary_efficiency = min(
        c[case]["minimum_secondary_only_efficiency"]
        for c in corners
        for case in ("reference", "qualification")
    )
    worst_rise = max(
        c[case]["maximum_cage_copper_rise_k"]
        for c in corners
        for case in ("reference", "qualification")
    )
    worst_current = max(
        c[case]["maximum_cage_current_density_a_m2"]
        for c in corners
        for case in ("reference", "qualification")
    )
    worst_slip = max(
        c[case]["maximum_cage_slip_m_s"]
        for c in corners
        for case in ("reference", "qualification")
    )
    worst_power = max(
        c[case]["maximum_peak_dc_power_w"]
        for c in corners
        for case in ("reference", "qualification")
    )
    worst_primary_rise = max(
        c[case]["maximum_primary_copper_rise_k"]
        for c in corners
        for case in ("reference", "qualification")
    )
    worst_frequency = max(
        c[case]["maximum_terminal_frequency_hz"]
        for c in corners
        for case in ("reference", "qualification")
    )
    worst_voltage = max(c["maximum_required_dc_link_v"] for c in corners)
    return f"""# A7a Gen2.5 cage/circuit reclosure

> **Generated by `tools/make_gen25_cage_circuit.py`. Do not hand-edit.**  
> Evidence class: **POST-FIELD HOMOGENIZED CAGE + LUMPED CIRCUIT/CG SHOT MODEL**.
> This is not transient field FEA or measurement.

## Result

**No robustness corner passes all 19 bands.** The failed-band union is: cage copper rise, cage
current density, reference source energy and secondary-only efficiency.

| Quantity | Worst A7a result | Frozen band | Outcome |
|---|---:|---:|---:|
| Reference source energy | {worst_reference_energy:.1f} J | <=900 J | **FAIL** |
| Qualification source energy | {worst_qualification_energy:.1f} J | <=1,500 J | PASS |
| Source-to-payload efficiency | {100*minimum_source_efficiency:.2f}% | >=30% | PASS |
| Secondary-only efficiency | {100*minimum_secondary_efficiency:.2f}% | >=50% | **FAIL** |
| Cage copper rise | {worst_rise:.2f} K | <=20 K | **FAIL** |
| Cage current density | {worst_current/1e6:.2f} A/mm2 | <=180 A/mm2 | **FAIL** |
| Cage slip | {worst_slip:.3f} m/s | <=8 m/s | PASS |
| Required DC link | {worst_voltage:.2f} V | <=48 V and >=10% margin | PASS |
| Peak DC power | {worst_power/1e3:.2f} kW | <=15 kW | PASS |
| Primary copper rise | {worst_primary_rise:.3f} K | <=3 K | PASS |
| Terminal frequency | {worst_frequency:.1f} Hz | <=350 Hz | PASS |
| Interface mass | {r['interface']['total_increment_kg']:.5f} kg | <=0.40 kg | PASS |

The failure is on the passive translator, not the drive. Voltage has more than 200% margin,
primary heat is negligible at this shot duration and worst power is below 12 kW. At the controlling
90% conductance corner, however, 7.073 m/s slip leaves only 45.66% secondary efficiency and drives
the qualification cage 2.74 K above its limit. The hot-resistance corner then pushes the reference
shot 5.1 J beyond the 900 J kill criterion.

## Disposition

**{r['disposition'].replace('_', ' ')}.** Keep the A6f field pass but reject the exact Gen2.5
cage/circuit point. The next change must lower force per conductive area or add conductor without
erasing the Fluxweb's magnetic continuity. Current and threshold increases are not the remedy.

The complete {r['cg_point_artifact']['record_count']:,}-point table is retained in
`{r['cg_point_artifact']['path']}`.

![A7a qualification cage-rise map](../analysis/figures/a7a/A7a_qualification_cage_rise_map.png)

![A7a controlling margins](../analysis/figures/a7a/A7a_controlling_margins.png)

See the immutable [A7a run sheet](../validation/A7a_gen25_cage_circuit.md).
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.write:
        OUTPUT.write_text(content, encoding="utf-8")
    elif args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            raise SystemExit("stale generated file: docs/GEN25_CAGE_CIRCUIT.md")
    else:
        print(content, end="")


if __name__ == "__main__":
    main()
