"""Render the A6 independently meshed nonlinear field result."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "analysis" / "results" / "gen2_field.json"
OUTPUT = ROOT / "docs" / "GEN2_FIELD.md"


def mark(value: bool) -> str:
    return "PASS" if value else "**FAIL**"


def render() -> str:
    result = json.loads(INPUT.read_text(encoding="utf-8"))
    fine = result["mesh_results"]["fine"]
    convergence = result["convergence"]
    bands = result["bands"]
    target = result["targets"]
    failed = ", ".join(name.replace("_", " ") for name in result["failed_bands"])
    p99 = fine["stationary_core_field_p99_t"]
    mean = fine["mean_tooth_slice_field_rms_t"]
    shortfall = 100.0 * (target["a3g_tooth_field_rms_t"] - mean) / target[
        "a3g_tooth_field_rms_t"
    ]
    return f"""# A6 Gen2 nonlinear transverse-field gate

> **Generated by `tools/make_gen2_field.py`. Do not hand-edit.**  
> Evidence class: **INDEPENDENTLY MESHED 2D NONLINEAR RMS-EQUIVALENT MAGNETOSTATIC FEA**.
> I treat this as model evidence, not measured field or force.

## What I found

**{result['band_pass_count']}/{result['band_count']} declared bands pass.** Failed bands:
{failed}.

| Quantity | Fine-mesh result | Frozen band | Outcome |
|---|---:|---:|---:|
| Base-to-fine mean-field change | {100 * convergence['base_to_fine_mean_slot_field_change_fraction']:.3f}% | <=2.000% | {mark(bands['mesh_mean_field_convergence'])} |
| Base-to-fine coenergy change | {100 * convergence['base_to_fine_coenergy_change_fraction']:.3f}% | <=4.000% | {mark(bands['mesh_coenergy_convergence'])} |
| Expanded-boundary mean-field change | {100 * convergence['base_to_expanded_boundary_mean_slot_field_change_fraction']:.3f}% | <=2.000% | {mark(bands['outer_boundary_sensitivity'])} |
| Mean tooth-slice field | {mean:.4f} T | 0.7200–0.8600 T | {mark(bands['mean_field_lower'] and bands['mean_field_upper'])} |
| Four-slot flux imbalance | {100 * fine['slot_to_slot_flux_imbalance_fraction']:.3f}% | <=5.000% | {mark(bands['slot_flux_balance'])} |
| Active-height field CV | {100 * fine['active_height_field_coefficient_of_variation']:.3f}% | <=15.000% | {mark(bands['active_height_field_uniformity'])} |
| Inferred ligament peak | {fine['inferred_maximum_ligament_field_t']:.4f} T | <=1.4500 T | {mark(bands['magnetic_ligament_field'])} |
| Stationary-core peak | {fine['stationary_core_maximum_field_t']:.4f} T | <=1.5500 T | {mark(bands['stationary_core_field'])} |
| Stationary-core area-weighted p99 | {p99:.4f} T | diagnostic | — |
| Per-cell inductance ratio to A3g | {result['fine_inductance_ratio_to_a3g']:.4f} | 0.7000–1.3000 | {mark(bands['inductance_lower'] and bands['inductance_upper'])} |
| Source-current residual | {fine['source_current_residual_fraction']:.3e} | <=1.000e-10 | {mark(bands['source_current_closure'])} |
| Final nonlinear solution change | {fine['final_relative_solution_change']:.3e} | <=1.000e-4 | {mark(bands['nonlinear_convergence'])} |

The fine mesh contains {fine['node_count']:,} nodes and {fine['element_count']:,} first-order
triangles. It converges in {fine['nonlinear_iteration_count']} nonlinear updates. Every retained
linear solve closes below the declared relative residual.

## What I found had failed—and what survived

The actual tooth-slice field is {shortfall:.1f}% below A3g's {target['a3g_tooth_field_rms_t']:.4f} T
target. Raising current into the same geometry is not an acceptable rescue: the stationary return
already reaches {fine['stationary_core_maximum_field_t']:.3f} T, and even its area-weighted p99 is
{p99:.3f} T. The independently integrated inductance is
{100 * (result['fine_inductance_ratio_to_a3g'] - 1):.1f}% above A3g, so the existing pulse-energy
and voltage point is no longer controlled.

The four-slot idea itself survives this gate. Slot imbalance, active-height uniformity, moving
ligament field, current closure, mesh convergence and outer-boundary sensitivity all pass. The
failure is concentrated in the stationary return geometry and the A3g lumped MMF/inductance
closure—not in nominal fit or in the passive Fluxbridge interface principle.

## What I decided next

**{result['disposition'].replace('_', ' ')}.**

A3g `p30_B0.56` is rejected as an operating point and must not control a drive, thermal or force
claim. Gen2 CAD remains useful as a fit-controlled starting geometry. Gen2.1 must redistribute
stationary return flux, recover mean blade field without overdriving the core, and rerun circuit
closure before any transient cage-force solve.

![Fine-mesh field magnitude](../analysis/figures/a6/A6_field_magnitude.png)

![Four-blade field distribution](../analysis/figures/a6/A6_blade_fields.png)

![Mesh and boundary convergence](../analysis/figures/a6/A6_convergence.png)

See the immutable [A6 run sheet](../validation/A6_gen2_field.md).
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.write:
        OUTPUT.write_text(content, encoding="utf-8")
    elif args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            raise SystemExit("stale generated file: docs/GEN2_FIELD.md")
    else:
        print(content, end="")


if __name__ == "__main__":
    main()
