"""Render the A6b Gen2.1 Fluxmanifold nonlinear field result."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "analysis" / "results" / "gen21_field.json"
OUTPUT = ROOT / "docs" / "GEN21_FIELD.md"


def mark(value: bool) -> str:
    return "PASS" if value else "**FAIL**"


def render() -> str:
    r = json.loads(INPUT.read_text(encoding="utf-8"))
    f = r["mesh_results"]["fine"]
    c = r["convergence"]
    b = r["bands"]
    failed = ", ".join(name.replace("_", " ") for name in r["failed_bands"])
    return f"""# A6b Gen2.1 Fluxmanifold field gate

> **Generated by `tools/make_gen21_field.py`. Do not hand-edit.**  
> Evidence class: **INDEPENDENTLY MESHED 2D NONLINEAR RMS-EQUIVALENT MAGNETOSTATIC FEA**.
> This is model evidence, not measured field or force.

## Result

**{r['band_pass_count']}/{r['band_count']} declared bands pass.** Failed bands: {failed}.

| Quantity | Fine-mesh result | Frozen band | Outcome |
|---|---:|---:|---:|
| Base-to-fine mean-field change | {100*c['base_to_fine_mean_slot_field_change_fraction']:.3f}% | <=2.000% | {mark(b['mesh_mean_field_convergence'])} |
| Base-to-fine coenergy change | {100*c['base_to_fine_coenergy_change_fraction']:.3f}% | <=4.000% | {mark(b['mesh_coenergy_convergence'])} |
| Expanded-boundary mean-field change | {100*c['base_to_expanded_boundary_mean_slot_field_change_fraction']:.3f}% | <=2.000% | {mark(b['outer_boundary_sensitivity'])} |
| Mean tooth-slice field | {f['mean_tooth_slice_field_rms_t']:.4f} T | 0.7200–0.8600 T | {mark(b['mean_field_lower'] and b['mean_field_upper'])} |
| Four-slot flux imbalance | {100*f['slot_to_slot_flux_imbalance_fraction']:.3f}% | <=5.000% | {mark(b['slot_flux_balance'])} |
| Active-height field CV | {100*f['active_height_field_coefficient_of_variation']:.3f}% | <=15.000% | {mark(b['active_height_field_uniformity'])} |
| Inferred ligament peak | {f['inferred_maximum_ligament_field_t']:.4f} T | <=1.4500 T | {mark(b['magnetic_ligament_field'])} |
| Stationary-core peak | {f['stationary_core_maximum_field_t']:.4f} T | <=1.5500 T | {mark(b['stationary_core_field'])} |
| Stationary-core area-weighted p99 | {f['stationary_core_field_p99_t']:.4f} T | diagnostic | — |
| Per-cell inductance ratio to A3g | {r['fine_inductance_ratio_to_a3g']:.4f} | 0.6800–1.0500 | {mark(b['inductance_lower'] and b['inductance_upper'])} |
| Source-current residual | {f['source_current_residual_fraction']:.3e} | <=1.000e-10 | {mark(b['source_current_closure'])} |
| Final nonlinear solution change | {f['final_relative_solution_change']:.3e} | <=1.000e-4 | {mark(b['nonlinear_convergence'])} |

The fine mesh contains {f['node_count']:,} nodes and {f['element_count']:,} triangles. It
converges in {f['nonlinear_iteration_count']} nonlinear updates.

## What changed from A6

Fluxmanifold repairs the main Gen2 failure. Mean field rises from 0.6568 to
{f['mean_tooth_slice_field_rms_t']:.4f} T. Core p99 falls from 1.5950 to
{f['stationary_core_field_p99_t']:.4f} T. The three-turn per-cell inductance is
{1e6*f['per_cell_inductance_h']:.4f} µH, inside its new frozen band. The radius-fed return is a
real improvement, not a relabelled A6 point.

It is not yet promotable. The fine moving-ligament estimate exceeds its limit by
{100*(f['inferred_maximum_ligament_field_t']/1.45-1):.2f}%, and the return-haunch peak exceeds its
limit by {100*(f['stationary_core_maximum_field_t']/1.55-1):.2f}%. Those small misses are resolved
on a numerically converged solution and remain failures.

## Disposition

**{r['disposition'].replace('_', ' ')}.**

Gen2.1 is retained as evidence that the manifold and turn exchange work, but its exact geometry
is rejected. Gen2.2 must reduce MMF and add genuine haunch area while remaining above the same
0.72 T field floor. No transient force, drive or CAD claim advances from A6b.

![A6b fine field](../analysis/figures/a6b/A6b_field_magnitude.png)

![A6b blade distribution](../analysis/figures/a6b/A6b_blade_fields.png)

![A6b convergence](../analysis/figures/a6b/A6b_convergence.png)

See the immutable [A6b run sheet](../validation/A6b_gen21_fluxmanifold.md).
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.write:
        OUTPUT.write_text(content, encoding="utf-8")
    elif args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            raise SystemExit("stale generated file: docs/GEN21_FIELD.md")
    else:
        print(content, end="")


if __name__ == "__main__":
    main()
