"""Render the A5d Gen2 CAD-fit result."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "analysis" / "results" / "gen2_cad_fit.json"
OUTPUT = ROOT / "docs" / "GEN2_CAD_FIT.md"


def render() -> str:
    result = json.loads(INPUT.read_text(encoding="utf-8"))
    g = result["geometry"]
    a = result["artifacts"]
    failed = ", ".join(name.replace("_", " ") for name in result["failed_bands"]) or "none"
    return f"""# A5d Gen2 CAD and fit gate

> **Generated by `tools/make_gen2_cad_fit.py`. Do not hand-edit.**  
> Evidence class: **PARAMETRIC CAD + EXACT NOMINAL SOLID INTERSECTION + ARCHIVE MANIFEST**.
> I do not present this as a tolerance study or manufacturing release.

## What I found

**{result['band_pass_count']}/{result['band_count']} declared bands pass.** Failed bands: {failed}.

| Quantity | Gen2 result |
|---|---:|
| Controlled A3g point | {result['selected_a3g_candidate_id']} |
| Payload envelope | {g['payload_envelope_mm'][0]:.1f} × {g['payload_envelope_mm'][1]:.1f} × {g['payload_envelope_mm'][2]:.1f} mm |
| Fluxbridge projection / fin side clearance | {g['fluxbridge_projection_mm']:.2f} / {g['nominal_fin_clearance_per_side_mm']:.2f} mm |
| Core footprint | {g['core_face_footprint_mm']:.1f} mm |
| Stator length / pitch / cell count | {g['active_stator_length_mm']:.0f} / {g['cell_pitch_mm']:.0f} mm / {g['cell_count_per_face']} |
| Two-sided gross winding fill | {100 * g['gross_winding_slot_fill_fraction']:.1f}% |
| Coil-to-Fluxbridge radial clearance | {g['coil_to_fluxbridge_radial_clearance_mm']:.2f} mm |
| Payload/stator intersection, four faces | {g['payload_stator_intersection_all_faces_mm3']:.6f} mm³ |
| Coil/core intersection, one face | {g['coil_core_intersection_per_face_mm3']:.6f} mm³ |
| Adjacent-coil overlap, one face | {g['adjacent_coil_overlap_per_face_mm3']:.6f} mm³ |
| Muzzle opening / frame envelope | {g['muzzle_opening_yz_mm']:.0f} / {g['assembly_frame_yz_mm']:.0f} mm |
| CAD / analytical copper volume | {g['cad_coil_volume_mm3']:.1f} / {g['analytical_copper_volume_mm3']:.1f} mm³ |
| Copper-volume error | {100 * g['coil_volume_relative_error']:.8f}% |
| STEP / STL / indexed renders | {a['step_count']} / {a['stl_count']} / {a['render_count']} |

## What I closed in A5d

Gen2 has a physical winding route. Adjacent 39 × 23 × 9 mm pack envelopes overlap axially in the
shared winding slot, but alternate between two radial layers. Their exact solid intersection is
zero; their exact intersection with the core is zero; and the lower layer clears the Fluxbridge
tip by 0.75 mm. The total CAD pack volume reproduces A3g's analytical copper volume to numerical
round-off.

The full-length interface remains the homogenized A3g representation. The 60 mm coupon separately
resolves 30 copper rungs, 30 magnetic ligaments, continuous root/tip buses and both winding layers.

## Download and regenerate

- [Gen2 STEP masters](../{a['step_archive']})
- [Gen2 STL previews](../{a['stl_archive']})

The archives are deterministic and verified member-by-member. Native source remains
`cad/build_gen2.py`; hashes, volumes, solid counts and bounds live in `cad/BUILD_GEN2.json`.

## What I decided next

**{result['disposition'].replace('_', ' ')}.**

A5d does not close the 0.20 mm tolerance stack, individual turns/insulation, end leads, cooling,
lamination manufacture, structure, provider acceptance or the homogenized-cage field assumption.

![Gen2 assembly](../cad/renders/gen2/01_gen2_hero.png)

See the immutable [A5d run sheet](../validation/A5d_gen2_cad.md).
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.write:
        OUTPUT.write_text(rendered, encoding="utf-8")
    elif args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            raise SystemExit("stale generated file: docs/GEN2_CAD_FIT.md")
    else:
        print(rendered, end="")


if __name__ == "__main__":
    main()
