"""Render the A7b Gen2.6 cage/circuit result."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "analysis" / "results" / "gen26_cage_circuit.json"
OUTPUT = ROOT / "docs" / "GEN26_CAGE_CIRCUIT.md"


def render() -> str:
    r = json.loads(INPUT.read_text(encoding="utf-8"))
    corners = r["corners"]
    worst_reference_energy = max(c["reference"]["maximum_source_energy_j"] for c in corners)
    worst_qualification_energy = max(c["qualification"]["maximum_source_energy_j"] for c in corners)
    minimum_source_efficiency = min(
        c[case]["minimum_source_to_payload_efficiency"]
        for c in corners
        for case in ("reference", "qualification")
    )
    minimum_secondary_efficiency = min(
        c[case]["minimum_secondary_only_efficiency"]
        for c in corners
        for case in ("reference", "qualification")
    )
    worst_rise = max(
        c[case]["maximum_cage_copper_rise_k"]
        for c in corners
        for case in ("reference", "qualification")
    )
    worst_current = max(
        c[case]["maximum_cage_current_density_a_m2"]
        for c in corners
        for case in ("reference", "qualification")
    )
    worst_slip = max(
        c[case]["maximum_cage_slip_m_s"]
        for c in corners
        for case in ("reference", "qualification")
    )
    worst_power = max(
        c[case]["maximum_peak_dc_power_w"]
        for c in corners
        for case in ("reference", "qualification")
    )
    worst_primary_rise = max(
        c[case]["maximum_primary_copper_rise_k"]
        for c in corners
        for case in ("reference", "qualification")
    )
    worst_frequency = max(
        c[case]["maximum_terminal_frequency_hz"]
        for c in corners
        for case in ("reference", "qualification")
    )
    worst_voltage = max(c["maximum_required_dc_link_v"] for c in corners)
    passing_corners = sum(c["pass"] for c in corners)

    low_sigma_cold = next(
        c for c in corners
        if c["corner"]["cage_sheet_conductance_multiplier"] == 0.9
        and c["corner"]["phase_resistance_multiplier"] == 1.0
    )
    low_sigma_hot = next(
        c for c in corners
        if c["corner"]["cage_sheet_conductance_multiplier"] == 0.9
        and c["corner"]["phase_resistance_multiplier"] == 1.25
    )
    cold_energy = low_sigma_cold["reference"]["maximum_source_energy_j"]
    hot_energy = low_sigma_hot["reference"]["maximum_source_energy_j"]
    base_resistance_energy = (hot_energy - cold_energy) / 0.25
    resistance_independent_energy = cold_energy - base_resistance_energy
    maximum_resistance_scale = (
        900.0 - resistance_independent_energy
    ) / (1.25 * base_resistance_energy)
    area_increase = 1.0 / maximum_resistance_scale - 1.0

    return f"""# A7b Gen2.6 Quintweb cage/circuit reclosure

> **Generated by `tools/make_gen26_cage_circuit.py`. Do not hand-edit.**  
> Evidence class: **POST-FIELD HOMOGENIZED CAGE + LUMPED CIRCUIT/CG SHOT MODEL**.
> I do not present this as transient field FEA or measurement.

## What I found

**I found {passing_corners}/4 robustness corners passing all 19 bands.** Both of my 100%
phase-resistance corners pass. Both 125% phase-resistance corners fail only my reference
source-energy band.

| Quantity | Worst A7b result | Frozen band | Outcome |
|---|---:|---:|---:|
| Reference source energy | {worst_reference_energy:.1f} J | <=900 J | **FAIL** |
| Qualification source energy | {worst_qualification_energy:.1f} J | <=1,500 J | PASS |
| Source-to-payload efficiency | {100*minimum_source_efficiency:.2f}% | >=30% | PASS |
| Secondary-only efficiency | {100*minimum_secondary_efficiency:.2f}% | >=50% | PASS |
| Cage copper rise | {worst_rise:.2f} K | <=20 K | PASS |
| Cage current density | {worst_current/1e6:.2f} A/mm2 | <=180 A/mm2 | PASS |
| Cage slip | {worst_slip:.3f} m/s | <=8 m/s | PASS |
| Required DC link | {worst_voltage:.2f} V | <=48 V and >=10% margin | PASS |
| Peak DC power | {worst_power/1e3:.2f} kW | <=15 kW | PASS |
| Primary copper rise | {worst_primary_rise:.3f} K | <=3 K | PASS |
| Terminal frequency | {worst_frequency:.1f} Hz | <=350 Hz | PASS |
| Interface mass | {r['interface']['total_increment_kg']:.5f} kg | <=0.40 kg | PASS |

I found that Quintweb closes every translator-side failure from A7a. At 90% cage conductance, maximum cage
rise falls from 22.74 K to {worst_rise:.2f} K, current density from 183.30 to
{worst_current/1e6:.2f} A/mm2 and slip from 7.073 to {worst_slip:.3f} m/s. Minimum secondary
efficiency rises from 45.66% to {100*minimum_secondary_efficiency:.2f}%.

My remaining miss is now on the stationary primary. The controlling 90%-conductance reference
corner uses {cold_energy:.1f} J at nominal phase resistance and {hot_energy:.1f} J at 125%.
The paired-corner difference isolates {base_resistance_energy:.1f} J of nominal-resistance
source energy and {resistance_independent_energy:.1f} J independent of that resistance. With all
other A7b quantities fixed, the nominal phase resistance must therefore fall to at most
{100*maximum_resistance_scale:.2f}% of A7b, equivalent to at least {100*area_increase:.2f}% more
effective copper area at unchanged turn length. That is a development diagnostic, not a frozen
Gen2.7 design.

## What I decided next

**{r['disposition'].replace('_', ' ')}.** I preserved the A6g field solution and the five-lane
translator. I rejected the exact Gen2.6 circuit point because my robustness claim requires all
four corners. I placed the next controlled change on the stationary launcher winding; adding
payload mass, raising current or moving my 900 J band would address the wrong failure.

I retain the complete {r['cg_point_artifact']['record_count']:,}-point table in
`{r['cg_point_artifact']['path']}`.

![A7b qualification cage-rise map](../analysis/figures/a7b/A7b_qualification_cage_rise_map.png)

![A7b controlling margins](../analysis/figures/a7b/A7b_controlling_margins.png)

See the immutable [A7b run sheet](../validation/A7b_gen26_cage_circuit.md).
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.write:
        OUTPUT.write_text(content, encoding="utf-8")
    elif args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            raise SystemExit("stale generated file: docs/GEN26_CAGE_CIRCUIT.md")
    else:
        print(content, end="")


if __name__ == "__main__":
    main()
