"""Render my A11 Fluxpiston flow result."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "analysis" / "results" / "fluxpiston_flow.json"
OUTPUT = ROOT / "docs" / "FLUXPISTON_FLOW.md"


def render() -> str:
    result = json.loads(INPUT.read_text(encoding="utf-8"))
    ref = result["case_summaries"]["reference"]
    qual = result["case_summaries"]["qualification"]
    campaign = result["campaign"]
    rows = []
    for check in result["checks"]:
        value = check["value"]
        shown = "no evidence" if value is None else f"{value:.6g}" if isinstance(value, float) else str(value)
        rows.append(f"| {check['id']}. {check['name']} | {shown} | **{check['status']}** |")
    return f"""# A11 Fluxpiston clearance and gas-flow screen

> **Generated by `tools/make_fluxpiston_flow.py`. Do not hand-edit.**  
> Evidence class: **IDEAL GAS + CONTINUUM CHOKED CLEARANCE-FLOW SCREEN**. I have not designed or
> validated a seal, valve, regulator, reservoir, pressure vessel or plume-control system.

## What I found

My model passes **{result['pass_count']}/8 executable frozen bands**. Band 9 remains OPEN by
construction.

| Band | Result | Status |
|---|---:|---|
{chr(10).join(rows)}

## The two gas cases

| Case | Gas exit | Mean chamber pressure | Acceleration | Headroom to 8 g | Shot time | EM trim energy |
|---|---:|---:|---:|---:|---:|---:|
| 4 kg reference | {ref['gas_velocity_m_s']:.2f} m/s | {ref['mean_chamber_pressure_pa']/1000:.3f} kPa | {ref['gas_acceleration_g']:.3f} g | {100*ref['pressure_headroom_fraction']:.2f}% | {1000*ref['shot_time_s']:.1f} ms | {ref['trim_kinetic_energy_j']:.3f} J |
| 6 kg qualification | {qual['gas_velocity_m_s']:.2f} m/s | {qual['mean_chamber_pressure_pa']/1000:.3f} kPa | {qual['gas_acceleration_g']:.3f} g | {100*qual['pressure_headroom_fraction']:.2f}% | {1000*qual['shot_time_s']:.1f} ms | {qual['trim_kinetic_energy_j']:.3f} J |

I stop the gas stage 0.25 m/s short in both cases. That buys real pressure/load margin and assigns
precision to the short electromagnetic section. The reference case controls pressure headroom;
the qualification case controls gas mass and feed area.

## What the deliberate leak costs

At the worst declared corner—{campaign['worst_corner']['case']},
{1000*campaign['worst_corner']['clearance_m']:.2f} mm clearance and
{campaign['worst_corner']['temperature_k']:.0f} K—I calculate
**{1000*campaign['worst_gas_mass_per_shot_kg']:.3f} g per shot** including chamber fill and
continuum choked leakage. Twelve shots use **{1000*campaign['campaign_gas_mass_kg']:.2f} g**.

That mass occupies an ideal-gas-equivalent **{1000*campaign['equivalent_reservoir_volume_m3_at_20bar_and_330k']:.3f} L**
at 20 bar and 330 K before tank wall, ullage, regulator floor, residuals or margin. The largest
equivalent 20 bar feed diameter is **{1000*campaign['maximum_supply_orifice_diameter_m']:.3f} mm**.

The result is promising for gas quantity and completely non-dispositive for seal physics. The
clearance is not a manufactured labyrinth, continuum flow may stop being adequate locally, and an
open perimeter can turn bypass gas into lateral force or contamination at exit.

## My disposition

I promote Fluxpiston to a dynamic regulator/chamber/blowdown model plus contact and plume gates. I
do not promote it to CAD. The next model must resolve valve response, pressure error and gas
temperature through the shot; the next physical article must measure leakage and force on a
representative perimeter coupon.

See my immutable [A11 run sheet](../validation/A11_fluxpiston_flow.md) and
[Gen6 definition](GENERATIONS.md).
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.write:
        OUTPUT.write_text(rendered, encoding="utf-8")
    elif args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            raise SystemExit("stale generated file: docs/FLUXPISTON_FLOW.md")
    else:
        print(rendered, end="")


if __name__ == "__main__":
    main()
