"""Render the A3b0 ideal edge-force summary from its committed JSON result."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "analysis" / "results" / "edge_force_bound.json"
OUTPUT = ROOT / "docs" / "EDGE_FORCE_BOUND.md"


def render() -> str:
    with INPUT.open(encoding="utf-8") as handle:
        result = json.load(handle)
    geometry = result["geometry"]
    force = result["force_bound"]
    failed = [name.replace("_", " ") for name, passed in result["bands"].items() if not passed]
    failed_text = ", ".join(failed) if failed else "none"
    return fr"""# A3b0 ideal edge-force bound

> **Generated by `tools/make_edge_force_bound.py`. Do not hand-edit.**  
> Evidence class: **ANALYTICAL UPPER BOUND with named EXTERNAL MATERIAL ANCHOR**. This is not
> FEA, a winding design or measurement.

## Outcome

The frozen three-fin channel contains **{geometry['simultaneously_active_overlap_edge_count']}**
ideal active tooth-overlap edges. For its **{geometry['effective_gap_per_side_m'] * 1e3:.2f} mm**
effective gap on each side and **{geometry['active_fin_height_m'] * 1e3:.1f} mm** fin height,
the gap-dominated energy-gradient bound is:

$$F_{{channel}} = {force['coefficient_n_per_t2']:.3f} B^2\;\mathrm{{N}}.$$

| Quantity | Result |
|---|---:|
| Required average channel force | {force['required_average_channel_force_n']:.1f} N |
| Required ideal gap flux density | {force['required_ideal_flux_density_t']:.3f} T |
| Ideal force at the optimistic 2.0 T ceiling | {force['ideal_force_at_optimistic_hard_ceiling_n']:.2f} N |
| Minimum fins at the 1.7 T preferred field | {force['minimum_fins_at_preferred_field']} |
| Minimum fins at the 2.0 T hard ceiling | {force['minimum_fins_at_hard_ceiling']} |

## Declared-band result

**{result['band_pass_count']}/{result['band_count']} A3b0 bands pass.** Failed bands: {failed_text}.

Disposition: **{result['disposition'].replace('_', ' ')}**.

## Why this reverses A5a promotion

A5a's 22.73 kPa figure divided required force by both long fin faces. That was a useful interface
area statistic, but it was not the axial Maxwell stress of a tooth-overlap reluctance machine.
Useful axial force is created by the change in overlap area at tooth edges. Even this calculation
gives every edge the requested field simultaneously and ignores every real loss mechanism; the
three-fin channel still misses 255 N at 2.0 T.

Do not spend FEA effort tuning this exact three-fin geometry. The next candidate must add active
edges, reduce effective gap or increase fin height, then repeat the interface screen before a
nonlinear 3D solve.

See the immutable [A3b0 run sheet](../validation/A3b0_edge_force_bound.md) and the
[manufacturer material anchor]({result['material_anchor']['url']}).
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.write:
        OUTPUT.write_text(rendered, encoding="utf-8")
    elif args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            raise SystemExit("stale generated file: docs/EDGE_FORCE_BOUND.md")
    else:
        print(rendered, end="")


if __name__ == "__main__":
    main()
