"""Render the A3b1 shared-pole throat summary from its committed result."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "analysis" / "results" / "stator_throat_bound.json"
OUTPUT = ROOT / "docs" / "STATOR_THROAT_BOUND.md"


def render() -> str:
    with INPUT.open(encoding="utf-8") as handle:
        result = json.load(handle)
    geometry = result["geometry"]
    flux = result["flux_bound"]
    resized = result["resized_shared_pole_array"]
    failed = [name.replace("_", " ") for name, passed in result["bands"].items() if not passed]
    failed_text = ", ".join(failed) if failed else "none"
    return f"""# A3b1 stationary pole-throat bound

> **Generated by `tools/make_stator_throat_bound.py`. Do not hand-edit.**  
> Evidence class: **ANALYTICAL FLUX-CONSERVATION UPPER BOUND**. I do not present this as FEA, a winding
> design or measurement.

## What I found

The A5b quad-comb moving interface survives, but its sketched **{geometry['drawn_pole_throat_width_m'] * 1e3:.1f} mm**
shared stationary webs do not. At the **{flux['required_ideal_gap_flux_density_t']:.3f} T** ideal
gap field, flux conservation requires **{flux['required_outer_throat_flux_density_t']:.2f} T** in
an outer throat and **{flux['required_interior_throat_flux_density_t']:.2f} T** in an interior
throat carrying two adjacent fin fluxes.

| Quantity | Result |
|---|---:|
| Hard throat-limited gap field | {flux['maximum_gap_flux_density_from_hard_interior_throat_t']:.3f} T |
| Ideal channel force at that field | {flux['ideal_force_at_throat_limited_gap_field_n']:.2f} N |
| Shared-pole footprint at 1.7 T | {resized['footprint_at_preferred_field_m'] * 1e3:.1f} mm |
| Share of usable face at 1.7 T | {100 * resized['usable_face_fraction_at_preferred_field']:.1f}% |
| Shared-pole footprint at optimistic 2.0 T | {resized['footprint_at_hard_field_m'] * 1e3:.1f} mm |
| Share of usable face at optimistic 2.0 T | {100 * resized['usable_face_fraction_at_hard_field']:.1f}% |

## What I found against my declared bands

**{result['band_pass_count']}/{result['band_count']} A3b1 bands pass.** Failed bands: {failed_text}.

Disposition: **{result['disposition'].replace('_', ' ')}**.

## What I decided next

Do not wrap a coil around the five-web sketch and call it a solved stator. Making its pole throats
wide enough consumes more than half of the usable face before winding space or tolerances. Bolley
therefore stops the shared-pole reluctance branch here and promotes the passive aluminium
induction interface already retained by A3a.

The quad-comb result remains useful as a record of what a cooperative ferromagnetic payload
interface costs. It is not the Gen1 baseline.

See the immutable [A3b1 run sheet](../validation/A3b1_stator_throat_bound.md).
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.write:
        OUTPUT.write_text(rendered, encoding="utf-8")
    elif args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            raise SystemExit("stale generated file: docs/STATOR_THROAT_BOUND.md")
    else:
        print(rendered, end="")


if __name__ == "__main__":
    main()
