"""Generate the controlled Gen2 dimensions and analytical BOM documents."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PARAMETERS = ROOT / "cad" / "gen2_parameters.json"
BUILD = ROOT / "cad" / "BUILD_GEN2.json"
A3F = ROOT / "analysis" / "results" / "fluxbridge_cage.json"
A3G = ROOT / "analysis" / "results" / "fluxbridge_optimization.json"
OUTPUTS = {
    ROOT / "cad" / "GEN2_DIMENSIONS.md": "dimensions",
    ROOT / "cad" / "GEN2_BOM.md": "bom",
}


def load(path: Path) -> dict:
    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


def render_dimensions(p: dict, build: dict, a3g: dict) -> str:
    payload = p["payload"]
    bridge = p["fluxbridge"]
    stator = p["stator"]
    track = p["track"]
    fit = build["fit_checks"]
    selected = a3g["selected_candidate"]["design"]
    return f"""# Gen2 controlled dimensions

> **Generated by `tools/make_gen2_cad_docs.py`. Do not hand-edit.**  
> Millimetres unless stated. `cad/gen2_parameters.json` is authoritative; figures are not.

## Coordinate frame

$+x$ is departure toward the muzzle, $y$ is lateral and $z$ is vertical. The origin is the aft
payload face at the retained position.

## Payload and passive interface

| Dimension | Value |
|---|---:|
| 3U envelope, x × y × z | {payload['envelope_length_x_mm']:.1f} × {payload['envelope_y_mm']:.1f} × {payload['envelope_z_mm']:.1f} |
| Corner rail width | {payload['corner_rail_width_mm']:.1f} |
| Fluxbridge active length | {bridge['active_length_x_mm']:.1f} |
| Blade centres across each face | {', '.join(f'{value:.1f}' for value in bridge['fin_centres_across_face_mm'])} |
| Blade thickness / projection | {bridge['fin_gross_thickness_mm']:.2f} / {bridge['encapsulated_total_projection_mm']:.2f} |
| Copper rung pitch / width | {bridge['bar_pitch_x_mm']:.2f} / {bridge['bar_axial_width_mm']:.2f} |
| Magnetic ligament width | {bridge['magnetic_ligament_axial_width_mm']:.2f} |
| Nominal fin clearance, each side | {fit['nominal_fin_clearance_per_side_mm']:.2f} |

## Primary cassette

| Dimension | Value |
|---|---:|
| Active length / cells per face | {stator['active_length_x_mm']:.1f} / {stator['cell_count_per_face']} |
| Pitch / wavelength | {stator['cell_pitch_x_mm']:.1f} / {stator['electrical_wavelength_mm']:.1f} |
| Tooth / winding slot | {stator['tooth_axial_width_mm']:.1f} / {stator['winding_slot_axial_width_mm']:.1f} |
| Foil slots | 4 × {stator['foil_slot_width_mm']:.2f} |
| Outer legs / interior separators | {stator['outer_return_leg_width_mm']:.1f} / {stator['interior_separator_width_mm']:.1f} |
| Face footprint / outer radial height | {stator['core_face_footprint_mm']:.1f} / {stator['outer_leg_radial_height_mm']:.1f} |
| Coil turns / conductor area | {stator['coil_turns_per_cell']} / {stator['conductor_area_per_turn_mm2']:.2f} mm² |
| Coil outer / inner mean spans | {stator['coil_outer_axial_span_mm']:.0f} × {stator['coil_outer_transverse_span_mm']:.0f} / {stator['coil_inner_axial_span_mm']:.0f} × {stator['coil_inner_transverse_span_mm']:.0f} |
| Coil layer height / number of layers | {stator['coil_layer_radial_height_mm']:.1f} / 2 |
| Two-sided gross slot fill | {100 * selected['gross_slot_fill_fraction']:.1f}% |
| Coil-to-blade-tip clearance | {fit['minimum_coil_to_fluxbridge_radial_clearance_mm']:.2f} |

## Launcher envelope

| Dimension | Value |
|---|---:|
| Track start / muzzle station | {track['start_x_mm']:.0f} / {track['muzzle_x_mm']:.0f} |
| Frame envelope | {track['enclosure_outer_yz_mm']:.0f} × {track['enclosure_outer_yz_mm']:.0f} |
| Open muzzle | {fit['muzzle_opening_yz_mm']:.0f} × {fit['muzzle_opening_yz_mm']:.0f} |

## Tolerances not yet defined

Only nominal geometry exists. Blade straightness, stator runout, core stacking, coil build,
encapsulation, vibration motion, thermal growth and four-face alignment require the later tolerance
gate. A nominal 0.20 mm side clearance is not permission to machine parts at ±0.20 mm.
"""


def render_bom(p: dict, build: dict, a3f: dict, a3g: dict) -> str:
    interface = a3f["interface"]
    primary = a3g["selected_candidate"]["design"]
    artifacts = build["artifacts"]
    return f"""# Gen2 analytical BOM

> **Generated by `tools/make_gen2_cad_docs.py`. Do not hand-edit.**  
> Masses marked MODEL are analytical. CAD volume is not silently converted to mass when material,
> fasteners or construction are unresolved.

| Qty | Item | Material / construction | Mass | Evidence | Status |
|---:|---|---|---:|---|---|
| 1 kit | Fluxbridge cage copper | Discrete rungs + root/tip buses | {interface['cage_copper_kg']:.3f} kg | A3f MODEL | Alloy/temper TBD |
| 1 kit | Fluxbridge magnetic matrix | 2605SA1-class laminated ribbon screen | {interface['magnetic_matrix_kg']:.3f} kg | A3f MODEL | Cutting/bonding process TBD |
| 1 kit | Interface capture + encapsulation allowance | Unselected | {interface['root_capture_and_encapsulation_allowance_kg']:.3f} kg | A3f ASSUMPTION | Detailed capture absent |
| 4 faces | Primary windings | Copper, four turns/cell | {primary['primary_copper_mass_kg']:.3f} kg | A3g MODEL | Insulation/leads absent |
| 4 faces | Stationary magnetic circuit | Laminated electrical steel placeholder | {primary['stationary_core_mass_kg']:.3f} kg | A3g MODEL | Grade/stack process TBD |
| 1 | Track + 160 mm frame | Unselected | TBD | CAD geometry only | Structure analysis absent |
| 1 | Independent gate | Unselected | TBD | CAD envelope only | Actuator/latch absent |
| 1 | Inverter + 48 V DC link | Unselected | TBD | Electrical envelope only | Supplier BOM absent |
| 1 | Cooling, sensors, cables and containment | Unselected | TBD | Not modelled | Required before build |

## Controlled analytical subtotals

| Subtotal | Mass |
|---|---:|
| Passive payload interface | {interface['total_increment_kg']:.3f} kg |
| Active primary copper + core | {primary['active_primary_mass_kg']:.3f} kg |
| Known modelled hardware, excluding bare payload | {interface['total_increment_kg'] + primary['active_primary_mass_kg']:.3f} kg |

The known subtotal is **not launcher dry mass**. It excludes every TBD row above. The CAD manifest
records volumes for traceability—for example the complete assembly proxy contains
{artifacts['Bolley_Assembly_Gen2']['volume_mm3'] / 1e6:.3f} L of overlapping material-labelled
solids—but that number is not a manufacturable volume or a valid mass roll-up.
"""


def rendered() -> dict[Path, str]:
    p, build, a3f, a3g = load(PARAMETERS), load(BUILD), load(A3F), load(A3G)
    return {
        path: render_dimensions(p, build, a3g)
        if kind == "dimensions"
        else render_bom(p, build, a3f, a3g)
        for path, kind in OUTPUTS.items()
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    files = rendered()
    if args.write:
        for path, content in files.items():
            path.write_text(content, encoding="utf-8")
    elif args.check:
        for path, content in files.items():
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                raise SystemExit(f"stale generated file: {path.relative_to(ROOT)}")
    else:
        for path, content in files.items():
            print(f"## {path.relative_to(ROOT)}\n\n{content}")


if __name__ == "__main__":
    main()
