"""Render the A3f Fluxbridge cage and compact-primary result."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "analysis" / "results" / "fluxbridge_cage.json"
OUTPUT = ROOT / "docs" / "FLUXBRIDGE_CAGE.md"


def render() -> str:
    result = json.loads(INPUT.read_text(encoding="utf-8"))
    interface = result["interface"]
    magnetic = result["rated_magnetic_circuit"]
    cage = result["rated_cage"]
    winding = result["winding"]
    mass = result["active_primary_mass"]
    drive = result["drive"]
    reference = result["reference_case"]["worst_source_energy_point"]
    qualification = result["qualification_case"]["worst_source_energy_point"]
    failed = ", ".join(name.replace("_", " ") for name in result["failed_bands"]) or "none"
    return f"""# A3f Fluxbridge passive cage

> **Generated by `tools/make_fluxbridge_cage.py`. Do not hand-edit.**  
> Evidence class: **HOMOGENIZED PASSIVE-CAGE + LUMPED MAGNETIC/CIRCUIT MODEL OUTPUT**. This is
> not field FEA, a winding drawing, supplier qualification or measurement.

## Result

**{result['band_pass_count']}/{result['band_count']} declared bands pass.** Failed bands: {failed}.

The Fluxbridge is a 1 mm passive blade made from a perforated soft-magnetic matrix and a shorted
copper ladder. The payload supplies no power, commands, magnets or connectors. It spends passive
interface mass to cut magnetic reluctance before the launcher has to buy that reluctance back in
copper.

| Quantity | A3f result |
|---|---:|
| Interface increment | {interface['total_increment_kg']:.3f} kg |
| Cage copper / magnetic matrix | {interface['cage_copper_kg']:.3f} / {interface['magnetic_matrix_kg']:.3f} kg |
| Equivalent cage copper sheet | {interface['cage_copper_equivalent_sheet_thickness_m'] * 1e3:.3f} mm |
| Equivalent / tooth / magnetic-ligament field | {magnetic['equivalent_sheet_field_rms_t']:.3f} / {magnetic['tooth_field_rms_t']:.3f} / {magnetic['magnetic_ligament_field_rms_t']:.3f} T RMS |
| Total MMF | {magnetic['total_mmf_a_turn']:.0f} A-turn |
| Turns / phase current | {winding['turns_per_cell']} / {winding['rated_phase_current_rms_a']:.1f} A RMS |
| Primary current density | {winding['rated_current_density_a_m2'] / 1e6:.1f} A/mm² |
| Two-sided winding-slot fill | {100 * winding['gross_slot_fill_fraction']:.1f}% |
| Phase R / L | {winding['phase_resistance_ohm'] * 1e3:.2f} mΩ / {winding['phase_inductance_h'] * 1e6:.2f} µH |
| Active primary copper / core / total | {mass['copper_kg']:.2f} / {mass['stationary_core_kg']:.2f} / {mass['total_kg']:.2f} kg |
| Rated cage slip / bar current density | {cage['slip_speed_m_s']:.2f} m/s / {cage['bar_current_density_rms_a_m2'] / 1e6:.1f} A/mm² |
| Common-mode normal load / 1% residual | {magnetic['normal_force_per_side_n']:.0f} / {magnetic['unbalanced_normal_force_n']:.1f} N |
| Maximum required DC link | {drive['maximum_required_dc_link_v']:.1f} V |

## Integrated shots

| Quantity | 4 kg bare reference | 6 kg bare qualification |
|---|---:|---:|
| Moving mass including interface | {reference['moving_mass_kg']:.3f} kg | {qualification['moving_mass_kg']:.3f} kg |
| Payload mechanical energy | {reference['mechanical_energy_j']:.1f} J | {qualification['mechanical_energy_j']:.1f} J |
| Cage copper energy | {reference['cage_copper_energy_j']:.1f} J | {qualification['cage_copper_energy_j']:.1f} J |
| Primary copper energy | {reference['primary_copper_energy_j']:.1f} J | {qualification['primary_copper_energy_j']:.1f} J |
| Stationary + moving magnetic loss | {reference['stationary_core_energy_j'] + reference['moving_matrix_energy_j']:.1f} J | {qualification['stationary_core_energy_j'] + qualification['moving_matrix_energy_j']:.1f} J |
| Source energy | {reference['source_energy_j']:.1f} J | {qualification['source_energy_j']:.1f} J |
| Source-to-payload efficiency | {100 * reference['source_to_payload_efficiency']:.1f}% | {100 * qualification['source_to_payload_efficiency']:.1f}% |
| Secondary-only efficiency | {100 * reference['secondary_only_efficiency']:.1f}% | {100 * qualification['secondary_only_efficiency']:.1f}% |
| Peak DC power | {reference['peak_dc_power_w'] / 1000:.2f} kW | {qualification['peak_dc_power_w'] / 1000:.2f} kW |
| Worst cage / primary copper rise | {reference['maximum_channel_cage_copper_adiabatic_rise_k']:.1f} / {reference['primary_copper_adiabatic_rise_k']:.2f} K | {qualification['maximum_channel_cage_copper_adiabatic_rise_k']:.1f} / {qualification['primary_copper_adiabatic_rise_k']:.2f} K |

## What the modification bought

Relative to A3e, rated MMF falls from 3,945 to {magnetic['total_mmf_a_turn']:.0f} A-turn and active
primary mass falls from 40.96 to {mass['total_kg']:.2f} kg. The CAD-discovered winding contradiction
becomes a {100 * winding['gross_slot_fill_fraction']:.1f}%-filled two-sided slot with insulation
allowance inside the frozen 65% limit.

It did **not** yet improve electrical efficiency. A3f spends {reference['source_energy_j']:.0f} J
on the reference shot versus A3e's 821 J because cage slip and a conservative high-current winding
remain expensive. The pass therefore promotes a pitch/field/copper optimisation—not a claim that
the first passing point is finished.

## Disposition

**{result['disposition'].replace('_', ' ')}.**

Field FEA must show that discrete bars, perforated ribbon, slotting and finite ends behave like the
homogenized model. Gen2 CAD must then prove the real four-turn coil, end turns, insulation and
0.20 mm gap without interference.

See the immutable [A3f run sheet](../validation/A3f_fluxbridge_cage.md).
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.write:
        OUTPUT.write_text(rendered, encoding="utf-8")
    elif args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            raise SystemExit("stale generated file: docs/FLUXBRIDGE_CAGE.md")
    else:
        print(rendered, end="")


if __name__ == "__main__":
    main()
